//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Gedo.ConsultaDocumentoCnn
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class ErrorConsultaNumeroSadeException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class responseExternalConsultaNumeroSade
    {
        
        private string estadoTareaField;
        
        private string idErrorField;
        
        private string motivoField;
        
        private string numeroSadeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string estadoTarea
        {
            get
            {
                return this.estadoTareaField;
            }
            set
            {
                this.estadoTareaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idError
        {
            get
            {
                return this.idErrorField;
            }
            set
            {
                this.idErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numeroSade
        {
            get
            {
                return this.numeroSadeField;
            }
            set
            {
                this.numeroSadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class requestExternalConsultarNumeroSade
    {
        
        private string idField;
        
        private string origenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class SinPrivilegiosException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class ErrorConsultaDocumentoException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class ParametroInvalidoConsultaException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class DocumentoNoExisteException
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", ConfigurationName="Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService")]
    public interface IExternalConsultaDocumentoMuleService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ErrorConsultaNumeroSadeException), Action="", Name="ErrorConsultaNumeroSadeException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarNumeroSadeResponse> consultarNumeroSadeAsync(Services.Gedo.ConsultaDocumentoCnn.consultarNumeroSade request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.SinPrivilegiosException), Action="", Name="SinPrivilegiosException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ErrorConsultaDocumentoException), Action="", Name="ErrorConsultaDocumentoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ParametroInvalidoConsultaException), Action="", Name="ParametroInvalidoConsultaException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.DocumentoNoExisteException), Action="", Name="DocumentoNoExisteException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPdfResponse> consultarDocumentoPdfAsync(Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPdf request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ErrorConsultaDocumentoException), Action="", Name="ErrorConsultaDocumentoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ParametroInvalidoConsultaException), Action="", Name="ParametroInvalidoConsultaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoEnExpedientesResponse> consultarDocumentoEnExpedientesAsync(Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoEnExpedientes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.SinPrivilegiosException), Action="", Name="SinPrivilegiosException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ErrorConsultaDocumentoException), Action="", Name="ErrorConsultaDocumentoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ParametroInvalidoConsultaException), Action="", Name="ParametroInvalidoConsultaException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.DocumentoNoExisteException), Action="", Name="DocumentoNoExisteException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPublicablePorNumeroResponse> consultarDocumentoPublicablePorNumeroAsync(Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPublicablePorNumero request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.SinPrivilegiosException), Action="", Name="SinPrivilegiosException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ErrorConsultaDocumentoException), Action="", Name="ErrorConsultaDocumentoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ParametroInvalidoConsultaException), Action="", Name="ParametroInvalidoConsultaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarTemporalPdfResponse> consultarTemporalPdfAsync(Services.Gedo.ConsultaDocumentoCnn.consultarTemporalPdf request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.SinPrivilegiosException), Action="", Name="SinPrivilegiosException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ErrorConsultaDocumentoException), Action="", Name="ErrorConsultaDocumentoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ParametroInvalidoConsultaException), Action="", Name="ParametroInvalidoConsultaException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.DocumentoNoExisteException), Action="", Name="DocumentoNoExisteException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPorNumeroResponse> consultarDocumentoPorNumeroAsync(Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPorNumero request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.ConsultaDocumentoCnn.ParametroInvalidoConsultaException), Action="", Name="ParametroInvalidoConsultaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoDetalleResponse> consultarDocumentoDetalleAsync(Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoDetalle request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNumeroSade", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarNumeroSade
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultarNumeroSade request;
        
        public consultarNumeroSade()
        {
        }
        
        public consultarNumeroSade(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultarNumeroSade request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNumeroSadeResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarNumeroSadeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.responseExternalConsultaNumeroSade @return;
        
        public consultarNumeroSadeResponse()
        {
        }
        
        public consultarNumeroSadeResponse(Services.Gedo.ConsultaDocumentoCnn.responseExternalConsultaNumeroSade @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class requestExternalConsultaDocumento
    {
        
        private bool assigneeField;
        
        private string numeroDocumentoField;
        
        private string numeroEspecialField;
        
        private string sistemaOrigenField;
        
        private string usuarioConsultaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool assignee
        {
            get
            {
                return this.assigneeField;
            }
            set
            {
                this.assigneeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string numeroEspecial
        {
            get
            {
                return this.numeroEspecialField;
            }
            set
            {
                this.numeroEspecialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sistemaOrigen
        {
            get
            {
                return this.sistemaOrigenField;
            }
            set
            {
                this.sistemaOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string usuarioConsulta
        {
            get
            {
                return this.usuarioConsultaField;
            }
            set
            {
                this.usuarioConsultaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentoPdf", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarDocumentoPdf
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request;
        
        public consultarDocumentoPdf()
        {
        }
        
        public consultarDocumentoPdf(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentoPdfResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarDocumentoPdfResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] @return;
        
        public consultarDocumentoPdfResponse()
        {
        }
        
        public consultarDocumentoPdfResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class requestExternalConsultaDocumentoEnExpediente
    {
        
        private string numeroDocumentoField;
        
        private string sistemaOrigenField;
        
        private string usuarioConsultaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sistemaOrigen
        {
            get
            {
                return this.sistemaOrigenField;
            }
            set
            {
                this.sistemaOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string usuarioConsulta
        {
            get
            {
                return this.usuarioConsultaField;
            }
            set
            {
                this.usuarioConsultaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class responseExternalConsultaDocumento
    {
        
        private string[] archivosDeTrabajoField;
        
        private string contenidoHtmlField;
        
        private string estadoValidezField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idTransaccionField;
        
        private bool idTransaccionFieldSpecified;
        
        private string[] listadoExpedientesField;
        
        private string motivoField;
        
        private int numeroDiasValidezField;
        
        private bool numeroDiasValidezFieldSpecified;
        
        private string numeroDocumentoField;
        
        private string numeroEspecialField;
        
        private string sistemaOrigenField;
        
        private string tipoDiaValidezField;
        
        private string tipoDocumentoField;
        
        private string tipoValidezField;
        
        private string urlArchivoField;
        
        private string usuarioGeneradorField;
        
        private string usuarioIniciadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("archivosDeTrabajo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] archivosDeTrabajo
        {
            get
            {
                return this.archivosDeTrabajoField;
            }
            set
            {
                this.archivosDeTrabajoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contenidoHtml
        {
            get
            {
                return this.contenidoHtmlField;
            }
            set
            {
                this.contenidoHtmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estadoValidez
        {
            get
            {
                return this.estadoValidezField;
            }
            set
            {
                this.estadoValidezField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCreacion
        {
            get
            {
                return this.fechaCreacionField;
            }
            set
            {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified
        {
            get
            {
                return this.fechaCreacionFieldSpecified;
            }
            set
            {
                this.fechaCreacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idTransaccion
        {
            get
            {
                return this.idTransaccionField;
            }
            set
            {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTransaccionSpecified
        {
            get
            {
                return this.idTransaccionFieldSpecified;
            }
            set
            {
                this.idTransaccionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listadoExpedientes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string[] listadoExpedientes
        {
            get
            {
                return this.listadoExpedientesField;
            }
            set
            {
                this.listadoExpedientesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int numeroDiasValidez
        {
            get
            {
                return this.numeroDiasValidezField;
            }
            set
            {
                this.numeroDiasValidezField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDiasValidezSpecified
        {
            get
            {
                return this.numeroDiasValidezFieldSpecified;
            }
            set
            {
                this.numeroDiasValidezFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string numeroEspecial
        {
            get
            {
                return this.numeroEspecialField;
            }
            set
            {
                this.numeroEspecialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string sistemaOrigen
        {
            get
            {
                return this.sistemaOrigenField;
            }
            set
            {
                this.sistemaOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tipoDiaValidez
        {
            get
            {
                return this.tipoDiaValidezField;
            }
            set
            {
                this.tipoDiaValidezField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string tipoValidez
        {
            get
            {
                return this.tipoValidezField;
            }
            set
            {
                this.tipoValidezField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string urlArchivo
        {
            get
            {
                return this.urlArchivoField;
            }
            set
            {
                this.urlArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string usuarioGenerador
        {
            get
            {
                return this.usuarioGeneradorField;
            }
            set
            {
                this.usuarioGeneradorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string usuarioIniciador
        {
            get
            {
                return this.usuarioIniciadorField;
            }
            set
            {
                this.usuarioIniciadorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentoEnExpedientes", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarDocumentoEnExpedientes
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumentoEnExpediente request;
        
        public consultarDocumentoEnExpedientes()
        {
        }
        
        public consultarDocumentoEnExpedientes(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumentoEnExpediente request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentoEnExpedientesResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarDocumentoEnExpedientesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.responseExternalConsultaDocumento @return;
        
        public consultarDocumentoEnExpedientesResponse()
        {
        }
        
        public consultarDocumentoEnExpedientesResponse(Services.Gedo.ConsultaDocumentoCnn.responseExternalConsultaDocumento @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentoPublicablePorNumero", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarDocumentoPublicablePorNumero
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request;
        
        public consultarDocumentoPublicablePorNumero()
        {
        }
        
        public consultarDocumentoPublicablePorNumero(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentoPublicablePorNumeroResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarDocumentoPublicablePorNumeroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.responseExternalConsultaDocumento @return;
        
        public consultarDocumentoPublicablePorNumeroResponse()
        {
        }
        
        public consultarDocumentoPublicablePorNumeroResponse(Services.Gedo.ConsultaDocumentoCnn.responseExternalConsultaDocumento @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class requestExternalConsultaTemporal
    {
        
        private string idWorkflowField;
        
        private string sistemaOrigenField;
        
        private string tipoDocumentoField;
        
        private string usuarioField;
        
        private string versionTipoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idWorkflow
        {
            get
            {
                return this.idWorkflowField;
            }
            set
            {
                this.idWorkflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sistemaOrigen
        {
            get
            {
                return this.sistemaOrigenField;
            }
            set
            {
                this.sistemaOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string versionTipoDocumento
        {
            get
            {
                return this.versionTipoDocumentoField;
            }
            set
            {
                this.versionTipoDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarTemporalPdf", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarTemporalPdf
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaTemporal request;
        
        public consultarTemporalPdf()
        {
        }
        
        public consultarTemporalPdf(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaTemporal request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarTemporalPdfResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarTemporalPdfResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] @return;
        
        public consultarTemporalPdfResponse()
        {
        }
        
        public consultarTemporalPdfResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentoPorNumero", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarDocumentoPorNumero
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request;
        
        public consultarDocumentoPorNumero()
        {
        }
        
        public consultarDocumentoPorNumero(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentoPorNumeroResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarDocumentoPorNumeroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.responseExternalConsultaDocumento @return;
        
        public consultarDocumentoPorNumeroResponse()
        {
        }
        
        public consultarDocumentoPorNumeroResponse(Services.Gedo.ConsultaDocumentoCnn.responseExternalConsultaDocumento @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class responseExternalConsultaDocumentoResponse
    {
        
        private campoFormularioDetalleResponse[] camposFormularioField;
        
        private documentoMetadataResponse[] datosPropiosField;
        
        private string estadoValidezField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private archivoDeTrabajoResponse[] listaArchivosDeTrabajoField;
        
        private string[] listaFirmantesField;
        
        private historialResponse[] listaHistorialField;
        
        private int numeroDiasValidezField;
        
        private bool numeroDiasValidezFieldSpecified;
        
        private string numeroEspecialField;
        
        private string numeroSadeField;
        
        private bool puedeVerDocumentoField;
        
        private bool puedeVerDocumentoFieldSpecified;
        
        private string referenciaField;
        
        private string tipoDiaValiezField;
        
        private string tipoDocumentoField;
        
        private string tipoValidezField;
        
        private string urlArchivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("campo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public campoFormularioDetalleResponse[] camposFormulario
        {
            get
            {
                return this.camposFormularioField;
            }
            set
            {
                this.camposFormularioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datosPropios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public documentoMetadataResponse[] datosPropios
        {
            get
            {
                return this.datosPropiosField;
            }
            set
            {
                this.datosPropiosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estadoValidez
        {
            get
            {
                return this.estadoValidezField;
            }
            set
            {
                this.estadoValidezField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCreacion
        {
            get
            {
                return this.fechaCreacionField;
            }
            set
            {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified
        {
            get
            {
                return this.fechaCreacionFieldSpecified;
            }
            set
            {
                this.fechaCreacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaArchivosDeTrabajo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public archivoDeTrabajoResponse[] listaArchivosDeTrabajo
        {
            get
            {
                return this.listaArchivosDeTrabajoField;
            }
            set
            {
                this.listaArchivosDeTrabajoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaFirmantes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string[] listaFirmantes
        {
            get
            {
                return this.listaFirmantesField;
            }
            set
            {
                this.listaFirmantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaHistorial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public historialResponse[] listaHistorial
        {
            get
            {
                return this.listaHistorialField;
            }
            set
            {
                this.listaHistorialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int numeroDiasValidez
        {
            get
            {
                return this.numeroDiasValidezField;
            }
            set
            {
                this.numeroDiasValidezField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDiasValidezSpecified
        {
            get
            {
                return this.numeroDiasValidezFieldSpecified;
            }
            set
            {
                this.numeroDiasValidezFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string numeroEspecial
        {
            get
            {
                return this.numeroEspecialField;
            }
            set
            {
                this.numeroEspecialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string numeroSade
        {
            get
            {
                return this.numeroSadeField;
            }
            set
            {
                this.numeroSadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool puedeVerDocumento
        {
            get
            {
                return this.puedeVerDocumentoField;
            }
            set
            {
                this.puedeVerDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool puedeVerDocumentoSpecified
        {
            get
            {
                return this.puedeVerDocumentoFieldSpecified;
            }
            set
            {
                this.puedeVerDocumentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string tipoDiaValiez
        {
            get
            {
                return this.tipoDiaValiezField;
            }
            set
            {
                this.tipoDiaValiezField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string tipoValidez
        {
            get
            {
                return this.tipoValidezField;
            }
            set
            {
                this.tipoValidezField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string urlArchivo
        {
            get
            {
                return this.urlArchivoField;
            }
            set
            {
                this.urlArchivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class campoFormularioDetalleResponse
    {
        
        private string etiquetaField;
        
        private itemComponenteDetalleResponse[] itemField;
        
        private string nombreField;
        
        private string separadorRepetidorField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string etiqueta
        {
            get
            {
                return this.etiquetaField;
            }
            set
            {
                this.etiquetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public itemComponenteDetalleResponse[] item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string separadorRepetidor
        {
            get
            {
                return this.separadorRepetidorField;
            }
            set
            {
                this.separadorRepetidorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class itemComponenteDetalleResponse
    {
        
        private string etiquetaField;
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string etiqueta
        {
            get
            {
                return this.etiquetaField;
            }
            set
            {
                this.etiquetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class documentoMetadataResponse : metadataResponse
    {
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentoMetadataResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class metadataResponse
    {
        
        private string nombreField;
        
        private bool obligatoriedadField;
        
        private int ordenField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool obligatoriedad
        {
            get
            {
                return this.obligatoriedadField;
            }
            set
            {
                this.obligatoriedadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int orden
        {
            get
            {
                return this.ordenField;
            }
            set
            {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class archivoDeTrabajoResponse
    {
        
        private byte[] dataArchivoField;
        
        private bool definitivoField;
        
        private System.DateTime fechaAsociacionField;
        
        private bool fechaAsociacionFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string idTaskField;
        
        private string nombreArchivoField;
        
        private string pathRelativoField;
        
        private string usuarioAsociadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] dataArchivo
        {
            get
            {
                return this.dataArchivoField;
            }
            set
            {
                this.dataArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool definitivo
        {
            get
            {
                return this.definitivoField;
            }
            set
            {
                this.definitivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaAsociacion
        {
            get
            {
                return this.fechaAsociacionField;
            }
            set
            {
                this.fechaAsociacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaAsociacionSpecified
        {
            get
            {
                return this.fechaAsociacionFieldSpecified;
            }
            set
            {
                this.fechaAsociacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idTask
        {
            get
            {
                return this.idTaskField;
            }
            set
            {
                this.idTaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombreArchivo
        {
            get
            {
                return this.nombreArchivoField;
            }
            set
            {
                this.nombreArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string pathRelativo
        {
            get
            {
                return this.pathRelativoField;
            }
            set
            {
                this.pathRelativoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string usuarioAsociador
        {
            get
            {
                return this.usuarioAsociadorField;
            }
            set
            {
                this.usuarioAsociadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/")]
    public partial class historialResponse
    {
        
        private string actividadField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string mensajeField;
        
        private string userNameField;
        
        private string usuarioField;
        
        private string workflowOrigenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string actividad
        {
            get
            {
                return this.actividadField;
            }
            set
            {
                this.actividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin
        {
            get
            {
                return this.fechaFinField;
            }
            set
            {
                this.fechaFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified
        {
            get
            {
                return this.fechaFinFieldSpecified;
            }
            set
            {
                this.fechaFinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaInicio
        {
            get
            {
                return this.fechaInicioField;
            }
            set
            {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified
        {
            get
            {
                return this.fechaInicioFieldSpecified;
            }
            set
            {
                this.fechaInicioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string workflowOrigen
        {
            get
            {
                return this.workflowOrigenField;
            }
            set
            {
                this.workflowOrigenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentoDetalle", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarDocumentoDetalle
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request;
        
        public consultarDocumentoDetalle()
        {
        }
        
        public consultarDocumentoDetalle(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDocumentoDetalleResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", IsWrapped=true)]
    public partial class consultarDocumentoDetalleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.consulta/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.ConsultaDocumentoCnn.responseExternalConsultaDocumentoResponse @return;
        
        public consultarDocumentoDetalleResponse()
        {
        }
        
        public consultarDocumentoDetalleResponse(Services.Gedo.ConsultaDocumentoCnn.responseExternalConsultaDocumentoResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IExternalConsultaDocumentoMuleServiceChannel : Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ExternalConsultaDocumentoMuleServiceClient : System.ServiceModel.ClientBase<Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService>, Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ExternalConsultaDocumentoMuleServiceClient() : 
                base(ExternalConsultaDocumentoMuleServiceClient.GetDefaultBinding(), ExternalConsultaDocumentoMuleServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IExternalConsultaDocumentoServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalConsultaDocumentoMuleServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ExternalConsultaDocumentoMuleServiceClient.GetBindingForEndpoint(endpointConfiguration), ExternalConsultaDocumentoMuleServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalConsultaDocumentoMuleServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ExternalConsultaDocumentoMuleServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalConsultaDocumentoMuleServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ExternalConsultaDocumentoMuleServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalConsultaDocumentoMuleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarNumeroSadeResponse> Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService.consultarNumeroSadeAsync(Services.Gedo.ConsultaDocumentoCnn.consultarNumeroSade request)
        {
            return base.Channel.consultarNumeroSadeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarNumeroSadeResponse> consultarNumeroSadeAsync(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultarNumeroSade request)
        {
            Services.Gedo.ConsultaDocumentoCnn.consultarNumeroSade inValue = new Services.Gedo.ConsultaDocumentoCnn.consultarNumeroSade();
            inValue.request = request;
            return ((Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService)(this)).consultarNumeroSadeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPdfResponse> Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService.consultarDocumentoPdfAsync(Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPdf request)
        {
            return base.Channel.consultarDocumentoPdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPdfResponse> consultarDocumentoPdfAsync(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request)
        {
            Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPdf inValue = new Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPdf();
            inValue.request = request;
            return ((Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService)(this)).consultarDocumentoPdfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoEnExpedientesResponse> Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService.consultarDocumentoEnExpedientesAsync(Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoEnExpedientes request)
        {
            return base.Channel.consultarDocumentoEnExpedientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoEnExpedientesResponse> consultarDocumentoEnExpedientesAsync(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumentoEnExpediente request)
        {
            Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoEnExpedientes inValue = new Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoEnExpedientes();
            inValue.request = request;
            return ((Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService)(this)).consultarDocumentoEnExpedientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPublicablePorNumeroResponse> Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService.consultarDocumentoPublicablePorNumeroAsync(Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPublicablePorNumero request)
        {
            return base.Channel.consultarDocumentoPublicablePorNumeroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPublicablePorNumeroResponse> consultarDocumentoPublicablePorNumeroAsync(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request)
        {
            Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPublicablePorNumero inValue = new Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPublicablePorNumero();
            inValue.request = request;
            return ((Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService)(this)).consultarDocumentoPublicablePorNumeroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarTemporalPdfResponse> Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService.consultarTemporalPdfAsync(Services.Gedo.ConsultaDocumentoCnn.consultarTemporalPdf request)
        {
            return base.Channel.consultarTemporalPdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarTemporalPdfResponse> consultarTemporalPdfAsync(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaTemporal request)
        {
            Services.Gedo.ConsultaDocumentoCnn.consultarTemporalPdf inValue = new Services.Gedo.ConsultaDocumentoCnn.consultarTemporalPdf();
            inValue.request = request;
            return ((Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService)(this)).consultarTemporalPdfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPorNumeroResponse> Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService.consultarDocumentoPorNumeroAsync(Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPorNumero request)
        {
            return base.Channel.consultarDocumentoPorNumeroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPorNumeroResponse> consultarDocumentoPorNumeroAsync(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request)
        {
            Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPorNumero inValue = new Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoPorNumero();
            inValue.request = request;
            return ((Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService)(this)).consultarDocumentoPorNumeroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoDetalleResponse> Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService.consultarDocumentoDetalleAsync(Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoDetalle request)
        {
            return base.Channel.consultarDocumentoDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoDetalleResponse> consultarDocumentoDetalleAsync(Services.Gedo.ConsultaDocumentoCnn.requestExternalConsultaDocumento request)
        {
            Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoDetalle inValue = new Services.Gedo.ConsultaDocumentoCnn.consultarDocumentoDetalle();
            inValue.request = request;
            return ((Services.Gedo.ConsultaDocumentoCnn.IExternalConsultaDocumentoMuleService)(this)).consultarDocumentoDetalleAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IExternalConsultaDocumentoServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IExternalConsultaDocumentoServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://mule.gdecapacitacion.lapampa.gob.ar/GEDOServices/consultaDocumento");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ExternalConsultaDocumentoMuleServiceClient.GetBindingForEndpoint(EndpointConfiguration.IExternalConsultaDocumentoServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ExternalConsultaDocumentoMuleServiceClient.GetEndpointAddress(EndpointConfiguration.IExternalConsultaDocumentoServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            IExternalConsultaDocumentoServicePort,
        }
    }
}
