using DataTransferObject;
using DataTransferObject.BLs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Business.Interfaces
{
    public interface ITramitesBL
    {
        Task<TramitesDTO> GetTramiteByGuidAsync(string IdentificadorUnico);
        Task<TramitesDTO> GetTramiteByIdAsync(int IdTramite);
        Task<TramitesDTO> CrearTramiteAsync(int IdTipoTramite);
        Task<TramitesDTO> CrearTramiteCertParaLicitarAsync(int IdObraPciaLP);
        Task<TramitesDTO> CrearTramiteActualizacionAsync(int IdTipoTramite, int IdEmpresa);
        Task<List<TramitesDTO>> GetTramitesByEmpresaAsync(int IdEmpresa);
        Task ActualizarTramiteAsync(TramitesDTO tramite);
        Task AprobarTramiteAsync(TramitesDTO tramite);
        Task ActualizarTramiteSinDatosFormAsync(int IdTramite, int NroFormulario, bool value);
        Task ActualizarEstadoTramiteAsync(int IdTramite, int IdEstado);
        Task<Dictionary<int, bool>> GetFormularioGuardadoAsync(int IdTramite);
        Task AgregarEspecialidadAsync(int IdTramite, int IdEspecialidad, int IdSeccion, List<int> lstTareas);
        Task ActualizarEspecialidadAsync(int IdTramite, int IdEspecialidad, int IdSeccion, List<int> lstTareas);
        Task<List<ItemGrillaEspecialidadesDTO>> GetEspecialidadesAsync(int IdTramite);
        Task<ItemGrillaEspecialidadesDTO> GetEspecialidadAsync(int IdTramiteEspecialidad);
        Task EliminarEspecialidadSeccionAsync(int IdTramiteEspecialidad);
        Task<List<ItemGrillaConsultarTramitesDTO>> GetTramitesGrillaByEmpresaAsync(int IdEmpresa);
        Task<List<ItemGrillaMisCertificadosDTO>> GetCertificadosGrillaByEmpresaAsync(int IdEmpresa);
        Task<List<ItemGrillaBandejaDTO>> GetTramitesBandejaAsync(string userid);
        Task<List<TramiteFormularioEvaluadoDTO>> GetFormulariosEvaluadosAsync(int IdTramite, int NroNotificacion);
        Task<List<TramiteFormularioEvaluadoDTO>> GetFormulariosEvaluadosAsync(int IdTramite);
        Task<TramitesRepresentanteTecnicoDTO> GetRepresentanteAsync(int IdRepresentanteTecnico);
        Task<List<TramitesRepresentanteTecnicoDTO>> GetRepresentantesAsync(int IdTramite);
        Task AgregarRepresentanteTecnicoAsync(TramitesRepresentanteTecnicoDTO representante);
        Task ActualizarRepresentanteTecnicoAsync(TramitesRepresentanteTecnicoDTO representante);
        Task EliminarRepresentanteTecnicoAsync(int IdRepresentanteTecnico);
        Task AgregarInfEmpDocumentoAsync(TramitesInfEmpDocumentoDTO documento);
        Task<TramitesInfEmpDTO> GetInfEmpAsync(int IdTramite);
        Task<List<TramitesInfEmpDocumentoDTO>> GetInfEmpDocumentosAsync(int IdTramite);
        Task EliminarInfEmpDocumentoAsync(int IdInfEmpDocumento);
        Task ActualizarInfEmpAsync(TramitesInfEmpDTO dto);
        Task AgregarInfEmpDeudaAsync(TramitesInfEmpDeudaDTO dto);
        Task EliminarInfEmpDeudaAsync(int IdTramiteInfEmpDeuda);
        Task<List<TramitesInfEmpDeudaDTO>> GetInfEmpDeudasAsync(int IdTramite);
        Task ActualizarBalanceGeneralAsync(TramitesBalanceGeneralDTO dto);
        Task<TramitesBalanceGeneralDTO> GetBalanceGeneralAsync(int IdTramiteBalanceGeneral);
        Task<List<TramitesBalanceGeneralDTO>> GetBalancesGeneralesAsync(int IdTramite);
        Task EliminarBalanceGeneralAsync(int IdTramite, int Anio);
        Task<TramitesEquipoDTO> GetEquiposAsync(int IdTramite, bool Afectado);
        Task EliminarEquipoAsync(int IdTramite, bool Afectado);
        Task ActualizarEquipoAsync(List<TramitesEquipoDTO> dto);
        Task<TramitesBienesRaicesDTO> GetBienesRaicesAsync(int IdTramite, bool Afectado);
        Task ActualizarBienRaizAsync(List<TramitesBienesRaicesDTO> dto, int IdTramite, bool SinDatosForm);
        Task EliminarBienRaizAsync(int IdTramite, bool Afectado);
        Task<List<TramitesObrasDTO>> GetObrasAsync(int IdTramite);
        Task<TramitesObrasDTO> GetObraAsync(int IdTramiteObra);
        Task AgregarObraAsync(TramitesObrasDTO dto);
        Task ActualizarObraAsync(TramitesObrasDTO dto);
        Task EliminarObraAsync(int IdTramiteObra);
        Task<List<TramitesObraEjecucionDTO>> GetObrasEjecucionAsync(int IdTramite);
        Task<TramitesObraEjecucionDTO> GetObraEjecucionAsync(int IdTramiteObraEjecucion);
        Task AgregarObraEjecucionAsync(TramitesObraEjecucionDTO dto);
        Task ActualizarObraEjecucionAsync(TramitesObraEjecucionDTO dto);
        Task EliminarObraEjecucionAsync(int IdTramiteObraEjecucion);
        Task<List<string>> ValidacionesPresentarTramite(int IdTramite);
        Task<TramitesDTO> GetTramitePendienteAsync(int IdGrupoTramite, int IdEmpresa);
        Task<TramitesDTO> ThrowIfValidacionesActualizacionAnual(int IdTipoTramite, int IdEmpresa);
        Task<TramitesDTO> GetUltimoTramiteAprobadoAsync(int IdTipoTramite, int IdEmpresa);
        Task<TramitesRepresentanteTecnicoDTO> GetRepresentanteTecnicoByCuitAsync(decimal cuit);
        Task TomarTramiteAsync(int IdTramite);
        Task<bool> ComprobarSeguridad(string IdentificadorUnico);
        Task<List<ItemGrillaConsultaTramiteDTO>> GetTramitesAsync(FilterConsultaTramitesDTO filter, int skip, int cantidadRegistros, out int TotalCount);
        Task<bool> isEvaluandoTramite(string IdentificadorUnico);
        Task<List<InformeRepresentanteTecnicoDTO>> GetInformeRepresentantesTecnicos1Async(FiltroInformeResponsablesTecnicosDTO filtro, CancellationToken cancellationToken = default);
        Task<DateTime> GetFechaVencimientoConstanciaInscripcion(int IdTramite);
        Task<DateTime?> GetFechaPresentacionAsync(int IdTramite);
        Task<DateTime?> GetFechaCertificacionAsync(int IdTramite);
        Task<TramitesDTO> GetUltimoTramiteAprobadoAsync(int IdEmpresa);
        Task ThrowIfValidacionesActualizacionCapacidadRespEquipos(int IdTipoTramite, int IdEmpresa);
        Task ActualizarInfEmpConsAsync(TramitesInfEmpConsDto dto);
        Task<TramitesInfEmpConsDto> GetInfEmpConsAsync(int IdTramite);
        Task<List<TramitesInfEmpConsDocumentoDto>> GetInfEmpConsDocumentosAsync(int IdTramite);
        Task ActualizarEspecialidadesRecoAsync(int IdTramite, List<EspecialidadSeccionDTO> lstEspecialidadesSecciones);
        Task<TramitesInfEmpDeudaDTO> GetInfEmpDeudaAsync(int IdTramiteInfEmpDeuda);
        Task ActualizarInfEmpDeudaAsync(TramitesInfEmpDeudaDTO dto);
        Task<TramitesInfEmpConsDeudaDto> GetInfEmpConsDeudaAsync(int IdTramiteInfEmpConsDeuda);
        Task<List<TramitesInfEmpConsDeudaDto>> GetInfEmpConsDeudasAsync(int IdTramite);
        Task ActualizarInfEmpConsDeudaAsync(TramitesInfEmpConsDeudaDto dto);
        Task AgregarInfEmpConsDeudaAsync(TramitesInfEmpConsDeudaDto dto);
        Task EliminarInfEmpConsDeudaAsync(int IdTramiteInfEmpConsDeuda);
        Task GuardarDesvinculacionRepresentanteTecnicoAsync(TramitesRepresentantesTecnicosDesvinculacionesDTO desvinculacion);
        Task EliminarDesvinculacionRepresentanteTecnicoAsync(int IdRepresentanteTecnico);
        Task ActualizarEnUte(int IdTramite, bool SePresentaEnUte, decimal? PorcParticipUte);
    }
}
