// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasInf
{
    public int IdEmpresaInf { get; set; }

    public int IdEmpresa { get; set; }

    public DateTime FechaInicioActividades { get; set; }

    public int? IdFileConstanciaInscImpNacionales { get; set; }

    public string? FilenameConstanciaInscImpNacionales { get; set; }

    public int? IdFileConstanciaBcra { get; set; }

    public string? FilenameConstanciaBcra { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual Files? IdFileConstanciaBcraNavigation { get; set; }

    public virtual Files? IdFileConstanciaInscImpNacionalesNavigation { get; set; }
}
