// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasSanciones
{
    public int IdEmpresaSancion { get; set; }

    public int IdEmpresa { get; set; }

    public string Nombre { get; set; } = null!;

    public int IdFileSancion { get; set; }

    public DateTime FechaDesdeSancion { get; set; }

    public DateTime? FechaHastaSancion { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual Files IdFileSancionNavigation { get; set; } = null!;
}
