// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasAntecedentesDdjjmensual
{
    public int IdEmpresaAntecedenteDdjjmensual { get; set; }

    public int IdEmpresaAntecedente { get; set; }

    public int Mes { get; set; }

    public int Anio { get; set; }

    public decimal Monto { get; set; }

    public virtual EmpresasAntecedentes IdEmpresaAntecedenteNavigation { get; set; } = null!;
}
