// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasEquipos
{
    public int IdEmpresaEquipo { get; set; }

    public int IdEmpresa { get; set; }

    public bool Afectado { get; set; }

    public int IdFileDetalleEquipo { get; set; }

    public string FilenameDetalleEquipo { get; set; } = null!;

    public int IdFileCertificadoContable { get; set; }

    public string FilenameCertificadoContable { get; set; } = null!;

    public int? IdFileDocumentacionEquipo { get; set; }

    public string? FilenameDocumentacionEquipo { get; set; }

    public decimal MontoRealizacion { get; set; }

    public decimal? MontoRealizacionEvaluador { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual Files IdFileCertificadoContableNavigation { get; set; } = null!;

    public virtual Files IdFileDetalleEquipoNavigation { get; set; } = null!;

    public virtual Files? IdFileDocumentacionEquipoNavigation { get; set; }
}
