// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasRepresentantesTecnicosJurisdicciones
{
    public int IdEmpresaRepresentanteTecnicoJurisdiccion { get; set; }

    public int IdEmpresaRepresentanteTecnico { get; set; }

    public int IdProvincia { get; set; }

    public virtual EmpresasRepresentantesTecnicos IdEmpresaRepresentanteTecnicoNavigation { get; set; } = null!;

    public virtual Provincias IdProvinciaNavigation { get; set; } = null!;
}
