// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasDetalleObrasEjecucion
{
    public int IdEmpresaDetalleObrasEjecucion { get; set; }

    public int IdEmpresa { get; set; }

    public int IdObraPciaLp { get; set; }

    public string ObraNombre { get; set; } = null!;

    public string? Comitente { get; set; }

    public string? PeríodoBase { get; set; }

    public decimal TotalContratado { get; set; }

    public decimal TotalCertificado { get; set; }

    public int Plazo { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime FechaCertificacion { get; set; }

    public int DiasTranscurridos { get; set; }

    public decimal MontoMensual { get; set; }

    public decimal MontoAnual { get; set; }

    public decimal CoefCertificado { get; set; }

    public decimal PorcentajeCertificado { get; set; }

    public decimal PorcentajeTiempo { get; set; }

    public decimal CoefMatriz { get; set; }

    public decimal CoefParticipacion { get; set; }

    public decimal MontoComprometido { get; set; }

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual ObrasProvinciaLaPampa IdObraPciaLpNavigation { get; set; } = null!;
}
