// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasInfDocumentos
{
    public int IdEmpresaInfDocumento { get; set; }

    public int IdEmpresa { get; set; }

    public int IdTipoDocumento { get; set; }

    public int IdFile { get; set; }

    public string Filename { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual Files IdFileNavigation { get; set; } = null!;

    public virtual TiposDeDocumentos IdTipoDocumentoNavigation { get; set; } = null!;
}
