// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasRepresentantesTecnicosDesvinculaciones
{
    public int IdEmpresaDesvinculacion { get; set; }

    public int IdEmpresa { get; set; }

    public int IdGrupoTramite { get; set; }

    public string Apellido { get; set; } = null!;

    public string Nombres { get; set; } = null!;

    public decimal Cuit { get; set; }

    public string Cargo { get; set; } = null!;

    public string Matricula { get; set; } = null!;

    public DateTime FechaVencimientoMatricula { get; set; }

    public DateTime FechaVencimientoContrato { get; set; }

    public int IdFileContrato { get; set; }

    public string FilenameContrato { get; set; } = null!;

    public int IdFileBoleta { get; set; }

    public string FilenameBoleta { get; set; } = null!;

    public int IdFileMatricula { get; set; }

    public string FilenameMatricula { get; set; } = null!;

    public int IdFileDesvinculacion { get; set; }

    public string FilenameDesvinculacion { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual Files IdFileBoletaNavigation { get; set; } = null!;

    public virtual Files IdFileContratoNavigation { get; set; } = null!;

    public virtual Files IdFileDesvinculacionNavigation { get; set; } = null!;

    public virtual Files IdFileMatriculaNavigation { get; set; } = null!;
}
