// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasCapTecxEquipo
{
    public int IdEmpresaCapTecxEquipo { get; set; }

    public int IdEmpresa { get; set; }

    public int? IdSeccion { get; set; }

    public string? DescripcionSeccion { get; set; }

    public decimal? Importe { get; set; }

    public decimal? CoefCapacTecnicaxEquipo { get; set; }

    public decimal? MultiplicadorCapEconomica { get; set; }

    public decimal? ImporteResultante { get; set; }

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual EspecialidadesSecciones? IdSeccionNavigation { get; set; }
}
