// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasEspecialidades
{
    public int IdEmpresaEspecialidad { get; set; }

    public int IdEmpresa { get; set; }

    public int IdGrupoTramite { get; set; }

    public int IdEspecialidad { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual ICollection<EmpresasAntecedentes> EmpresasAntecedentes { get; set; } = new List<EmpresasAntecedentes>();

    public virtual ICollection<EmpresasEspecialidadesSecciones> EmpresasEspecialidadesSecciones { get; set; } = new List<EmpresasEspecialidadesSecciones>();

    public virtual ICollection<EmpresasObras> EmpresasObras { get; set; } = new List<EmpresasObras>();

    public virtual ICollection<EmpresasRepresentantesTecnicosEspecialidades> EmpresasRepresentantesTecnicosEspecialidades { get; set; } = new List<EmpresasRepresentantesTecnicosEspecialidades>();

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual Especialidades IdEspecialidadNavigation { get; set; } = null!;
}
