// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasEspecialidadesSecciones
{
    public int IdEmpresaEspecialidadSeccion { get; set; }

    public int IdEmpresaEspecialidad { get; set; }

    public int IdSeccion { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual ICollection<EmpresasAntecedentes> EmpresasAntecedentes { get; set; } = new List<EmpresasAntecedentes>();

    public virtual ICollection<EmpresasEspecialidadesTareas> EmpresasEspecialidadesTareas { get; set; } = new List<EmpresasEspecialidadesTareas>();

    public virtual ICollection<EmpresasObras> EmpresasObras { get; set; } = new List<EmpresasObras>();

    public virtual EmpresasEspecialidades IdEmpresaEspecialidadNavigation { get; set; } = null!;

    public virtual EspecialidadesSecciones IdSeccionNavigation { get; set; } = null!;
}
