// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasEspecialidadesEquipos
{
    public int IdEmpresaEspecialidadEquipo { get; set; }

    public int IdEmpresaEspecialidadTarea { get; set; }

    public int IdEquipo { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual EmpresasEspecialidadesTareas IdEmpresaEspecialidadTareaNavigation { get; set; } = null!;

    public virtual EspecialidadesEquipos IdEquipoNavigation { get; set; } = null!;
}
