// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasDeudas
{
    public int IdEmpresaDeuda { get; set; }

    public int IdEmpresa { get; set; }

    public int IdGrupoTramite { get; set; }

    public string Entidad { get; set; } = null!;

    public string Periodo { get; set; } = null!;

    public int Situacion { get; set; }

    public decimal Monto { get; set; }

    public int DiasDeAtraso { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;
}
