// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasObras
{
    public int IdEmpresaObra { get; set; }

    public int IdEmpresa { get; set; }

    public int IdEmpresaEspecialidad { get; set; }

    public int IdEmpresaEspecialidadSeccion { get; set; }

    public int IdObraPciaLp { get; set; }

    public string Comitente { get; set; } = null!;

    public int IdTipoObra { get; set; }

    public decimal Monto { get; set; }

    public string PeriodoBase { get; set; } = null!;

    public string PeriodoContrato { get; set; } = null!;

    public string PeriodoFin { get; set; } = null!;

    public int IdFile { get; set; }

    public string Filename { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual EmpresasEspecialidades IdEmpresaEspecialidadNavigation { get; set; } = null!;

    public virtual EmpresasEspecialidadesSecciones IdEmpresaEspecialidadSeccionNavigation { get; set; } = null!;

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual Files IdFileNavigation { get; set; } = null!;

    public virtual ObrasProvinciaLaPampa IdObraPciaLpNavigation { get; set; } = null!;

    public virtual TiposDeObras IdTipoObraNavigation { get; set; } = null!;
}
