// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasCapEjec
{
    public int IdEmpresaCapEjec { get; set; }

    public int IdEmpresa { get; set; }

    public int? IdSeccion { get; set; }

    public string? DescripcionSeccion { get; set; }

    public decimal? CapacidadEconomica { get; set; }

    public decimal? CapacidadProduccion { get; set; }

    public decimal? CapacidadEconomica080 { get; set; }

    public decimal? CapacidadProduccion020 { get; set; }

    public decimal? CapacidadEjecucion { get; set; }

    public decimal? CoeficienteConceptual { get; set; }

    public decimal? CapacidadEjecucionAnual { get; set; }

    public decimal? CoeficienteEstadoDeudaBcra { get; set; }

    public decimal? CapacidadEjecucionFinal { get; set; }

    public bool ExistsInForm1 { get; set; }

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual EspecialidadesSecciones? IdSeccionNavigation { get; set; }
}
