// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasAntecedentes
{
    public int IdEmpresaAntecedente { get; set; }

    public int IdEmpresa { get; set; }

    public int IdEmpresaEspecialidad { get; set; }

    public int IdEmpresaEspecialidadSeccion { get; set; }

    public int IdObraPciaLp { get; set; }

    public string Ubicacion { get; set; } = null!;

    public string Comitente { get; set; } = null!;

    public string PeriodoBase { get; set; } = null!;

    public string PeriodoInicio { get; set; } = null!;

    public int Plazo { get; set; }

    public decimal MontoContrato { get; set; }

    public decimal MontoEjecutado { get; set; }

    public decimal MontoAejecutar { get; set; }

    public string RepresentanteTecnico { get; set; } = null!;

    public int IdFile { get; set; }

    public string Filename { get; set; } = null!;

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public virtual ICollection<EmpresasAntecedentesDdjjmensual> EmpresasAntecedentesDdjjmensual { get; set; } = new List<EmpresasAntecedentesDdjjmensual>();

    public virtual EmpresasEspecialidades IdEmpresaEspecialidadNavigation { get; set; } = null!;

    public virtual EmpresasEspecialidadesSecciones IdEmpresaEspecialidadSeccionNavigation { get; set; } = null!;

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual Files IdFileNavigation { get; set; } = null!;

    public virtual ObrasProvinciaLaPampa IdObraPciaLpNavigation { get; set; } = null!;
}
