// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasCapTecnica
{
    public int IdEmpresaCapTecnica { get; set; }

    public int IdEmpresa { get; set; }

    public int? IdSeccion { get; set; }

    public string? DescripcionSeccion { get; set; }

    public decimal? Monto { get; set; }

    public int? Mes { get; set; }

    public int? Anio { get; set; }

    public decimal? CoefActualizacion { get; set; }

    public decimal? CoefTipoObra { get; set; }

    public decimal? CapacidadTecnicaxEquipo { get; set; }

    public decimal? CoerficienteConceptual { get; set; }

    public decimal? CapacidadTecnicaFinal { get; set; }

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual EspecialidadesSecciones? IdSeccionNavigation { get; set; }
}
