// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasObrasEjecucion
{
    public int IdEmpresaObraEjec { get; set; }

    public int IdEmpresa { get; set; }

    public string Expediente { get; set; } = null!;

    public int IdObraPciaLp { get; set; }

    public string Comitente { get; set; } = null!;

    public int IdTipoObra { get; set; }

    public string Ubicacion { get; set; } = null!;

    public string PeriodoBase { get; set; } = null!;

    public DateTime FechaInicio { get; set; }

    public decimal MontoMensual { get; set; }

    public decimal MontoAnual { get; set; }

    public decimal TotalContratado { get; set; }

    public decimal TotalCertificado { get; set; }

    public decimal Saldo { get; set; }

    public decimal PorcentajeCertificado { get; set; }

    public int PlazoObra { get; set; }

    public int PlazoAmpliacion { get; set; }

    public int IdFile { get; set; }

    public string Filename { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual Files IdFileNavigation { get; set; } = null!;

    public virtual ObrasProvinciaLaPampa IdObraPciaLpNavigation { get; set; } = null!;

    public virtual TiposDeObras IdTipoObraNavigation { get; set; } = null!;
}
