// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasBienesRaices
{
    public int IdEmpresaBienRaiz { get; set; }

    public int IdEmpresa { get; set; }

    public bool Afectado { get; set; }

    public int IdFileDetalleInmueble { get; set; }

    public string FilenameDetalleInmueble { get; set; } = null!;

    public int IdFileCertificadoContable { get; set; }

    public string FilenameCertificadoContable { get; set; } = null!;

    public decimal MontoRealizacion { get; set; }

    public decimal? MontoRealizacionEvaluador { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual Files IdFileCertificadoContableNavigation { get; set; } = null!;

    public virtual Files IdFileDetalleInmuebleNavigation { get; set; } = null!;
}
