// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasEspecialidadesTareas
{
    public int IdEmpresaEspecialidadTarea { get; set; }

    public int? IdEmpresaEspecialidadSeccion { get; set; }

    public int IdTarea { get; set; }

    public virtual ICollection<EmpresasEspecialidadesEquipos> EmpresasEspecialidadesEquipos { get; set; } = new List<EmpresasEspecialidadesEquipos>();

    public virtual EmpresasEspecialidadesSecciones? IdEmpresaEspecialidadSeccionNavigation { get; set; }

    public virtual EspecialidadesTareas IdTareaNavigation { get; set; } = null!;
}
