// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasRepresentantesTecnicosEspecialidades
{
    public int IdEmpresaRepresentanteEspecialidad { get; set; }

    public int IdEmpresaRepresentanteTecnico { get; set; }

    public int IdEmpresaEspecialidad { get; set; }

    public virtual EmpresasEspecialidades IdEmpresaEspecialidadNavigation { get; set; } = null!;

    public virtual EmpresasRepresentantesTecnicos IdEmpresaRepresentanteTecnicoNavigation { get; set; } = null!;
}
