// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EmpresasConstanciaCap
{
    public int IdEmpresaConstanciaCap { get; set; }

    public int IdEmpresa { get; set; }

    public int? IdSeccion { get; set; }

    public string? DescripcionSeccion { get; set; }

    public decimal? CapacidadTecnica { get; set; }

    public decimal? CapacidadTecnicaUvi { get; set; }

    public decimal? CapacidadContratacion { get; set; }

    public decimal? CapacidadContratacionUvi { get; set; }

    public decimal? EjecucaionAnual { get; set; }

    public decimal? EjecucaionAnualUvi { get; set; }

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual EspecialidadesSecciones? IdSeccionNavigation { get; set; }
}
