// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class Empresas
{
    public int IdEmpresa { get; set; }

    public decimal CuitEmpresa { get; set; }

    public string RazonSocial { get; set; } = null!;

    public string Domicilio { get; set; } = null!;

    public DateTime? FechaInscripcion { get; set; }

    public DateTime? Vencimiento { get; set; }

    public DateTime? FechaBalance { get; set; }

    public int? IdTramiteOrigen { get; set; }

    public string? UseridRepresentante { get; set; }

    public DateTime FechaVigenciaDesde { get; set; }

    public DateTime? FechaVigenciaHasta { get; set; }

    public DateTime? FechaInscripcionReco { get; set; }

    public DateTime? VencimientoReco { get; set; }

    public int? AniosAntiguedadReco { get; set; }

    public int? IdTramiteOrigenReco { get; set; }

    public DateTime? FechaVigenciaDesdeReco { get; set; }

    public DateTime? FechaVigenciaHastaReco { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual ICollection<EmpresasAntecedentes> EmpresasAntecedentes { get; set; } = new List<EmpresasAntecedentes>();

    public virtual ICollection<EmpresasBalancesGenerales> EmpresasBalancesGenerales { get; set; } = new List<EmpresasBalancesGenerales>();

    public virtual ICollection<EmpresasBalancesGeneralesEvaluar> EmpresasBalancesGeneralesEvaluar { get; set; } = new List<EmpresasBalancesGeneralesEvaluar>();

    public virtual ICollection<EmpresasBienesRaices> EmpresasBienesRaices { get; set; } = new List<EmpresasBienesRaices>();

    public virtual ICollection<EmpresasCapEjec> EmpresasCapEjec { get; set; } = new List<EmpresasCapEjec>();

    public virtual ICollection<EmpresasCapProd> EmpresasCapProd { get; set; } = new List<EmpresasCapProd>();

    public virtual ICollection<EmpresasCapTecnica> EmpresasCapTecnica { get; set; } = new List<EmpresasCapTecnica>();

    public virtual ICollection<EmpresasCapTecxEquipo> EmpresasCapTecxEquipo { get; set; } = new List<EmpresasCapTecxEquipo>();

    public virtual ICollection<EmpresasConstanciaCap> EmpresasConstanciaCap { get; set; } = new List<EmpresasConstanciaCap>();

    public virtual ICollection<EmpresasDetalleObrasEjecucion> EmpresasDetalleObrasEjecucion { get; set; } = new List<EmpresasDetalleObrasEjecucion>();

    public virtual ICollection<EmpresasDeudas> EmpresasDeudas { get; set; } = new List<EmpresasDeudas>();

    public virtual ICollection<EmpresasEquipos> EmpresasEquipos { get; set; } = new List<EmpresasEquipos>();

    public virtual ICollection<EmpresasEspecialidades> EmpresasEspecialidades { get; set; } = new List<EmpresasEspecialidades>();

    public virtual ICollection<EmpresasInf> EmpresasInf { get; set; } = new List<EmpresasInf>();

    public virtual ICollection<EmpresasInfDocumentos> EmpresasInfDocumentos { get; set; } = new List<EmpresasInfDocumentos>();

    public virtual ICollection<EmpresasObras> EmpresasObras { get; set; } = new List<EmpresasObras>();

    public virtual ICollection<EmpresasObrasEjecucion> EmpresasObrasEjecucion { get; set; } = new List<EmpresasObrasEjecucion>();

    public virtual ICollection<EmpresasRepresentantesTecnicos> EmpresasRepresentantesTecnicos { get; set; } = new List<EmpresasRepresentantesTecnicos>();

    public virtual ICollection<EmpresasRepresentantesTecnicosDesvinculaciones> EmpresasRepresentantesTecnicosDesvinculaciones { get; set; } = new List<EmpresasRepresentantesTecnicosDesvinculaciones>();

    public virtual ICollection<EmpresasSanciones> EmpresasSanciones { get; set; } = new List<EmpresasSanciones>();

    public virtual Tramites? IdTramiteOrigenNavigation { get; set; }

    public virtual Tramites? IdTramiteOrigenRecoNavigation { get; set; }

    public virtual ICollection<Tramites> Tramites { get; set; } = new List<Tramites>();
}
