// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EspecialidadesSecciones
{
    public int IdSeccion { get; set; }

    public string DescripcionSeccion { get; set; } = null!;

    public int IdEspecialidad { get; set; }

    public bool Baja { get; set; }

    public decimal? CoefCapacTecnicaxEquipo { get; set; }

    public decimal? MultiplicadorCapEconomica { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual ICollection<EmpresasCapEjec> EmpresasCapEjec { get; set; } = new List<EmpresasCapEjec>();

    public virtual ICollection<EmpresasCapProd> EmpresasCapProd { get; set; } = new List<EmpresasCapProd>();

    public virtual ICollection<EmpresasCapTecnica> EmpresasCapTecnica { get; set; } = new List<EmpresasCapTecnica>();

    public virtual ICollection<EmpresasCapTecxEquipo> EmpresasCapTecxEquipo { get; set; } = new List<EmpresasCapTecxEquipo>();

    public virtual ICollection<EmpresasConstanciaCap> EmpresasConstanciaCap { get; set; } = new List<EmpresasConstanciaCap>();

    public virtual ICollection<EmpresasEspecialidadesSecciones> EmpresasEspecialidadesSecciones { get; set; } = new List<EmpresasEspecialidadesSecciones>();

    public virtual ICollection<EspecialidadesTareas> EspecialidadesTareas { get; set; } = new List<EspecialidadesTareas>();

    public virtual Especialidades IdEspecialidadNavigation { get; set; } = null!;

    public virtual ICollection<TramitesBalancesGeneralesEvaluarCapEjec> TramitesBalancesGeneralesEvaluarCapEjec { get; set; } = new List<TramitesBalancesGeneralesEvaluarCapEjec>();

    public virtual ICollection<TramitesBalancesGeneralesEvaluarCapProd> TramitesBalancesGeneralesEvaluarCapProd { get; set; } = new List<TramitesBalancesGeneralesEvaluarCapProd>();

    public virtual ICollection<TramitesBalancesGeneralesEvaluarCapTecnica> TramitesBalancesGeneralesEvaluarCapTecnica { get; set; } = new List<TramitesBalancesGeneralesEvaluarCapTecnica>();

    public virtual ICollection<TramitesBalancesGeneralesEvaluarCapTecxEquipo> TramitesBalancesGeneralesEvaluarCapTecxEquipo { get; set; } = new List<TramitesBalancesGeneralesEvaluarCapTecxEquipo>();

    public virtual ICollection<TramitesBalancesGeneralesEvaluarConstanciaCap> TramitesBalancesGeneralesEvaluarConstanciaCap { get; set; } = new List<TramitesBalancesGeneralesEvaluarConstanciaCap>();

    public virtual ICollection<TramitesEspecialidadesSecciones> TramitesEspecialidadesSecciones { get; set; } = new List<TramitesEspecialidadesSecciones>();

    public virtual ICollection<EspecialidadesEquipos> IdEquipo { get; set; } = new List<EspecialidadesEquipos>();
}
