// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EspecialidadesTareas
{
    public int IdTarea { get; set; }

    public string DescripcionTarea { get; set; } = null!;

    public int IdSeccion { get; set; }

    public bool Baja { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual ICollection<EmpresasEspecialidadesTareas> EmpresasEspecialidadesTareas { get; set; } = new List<EmpresasEspecialidadesTareas>();

    public virtual EspecialidadesSecciones IdSeccionNavigation { get; set; } = null!;

    public virtual ICollection<TramitesEspecialidadesTareas> TramitesEspecialidadesTareas { get; set; } = new List<TramitesEspecialidadesTareas>();
}
