// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EspecialidadesEquipos
{
    public int IdEquipo { get; set; }

    public string DescripcionEquipo { get; set; } = null!;

    public bool Baja { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual ICollection<EmpresasEspecialidadesEquipos> EmpresasEspecialidadesEquipos { get; set; } = new List<EmpresasEspecialidadesEquipos>();

    public virtual ICollection<TramitesEspecialidadesEquipos> TramitesEspecialidadesEquipos { get; set; } = new List<TramitesEspecialidadesEquipos>();

    public virtual ICollection<EspecialidadesSecciones> IdSeccion { get; set; } = new List<EspecialidadesSecciones>();
}
