// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class Especialidades
{
    public int IdEspecialidad { get; set; }

    public string NombreEspecialidad { get; set; } = null!;

    public string Rama { get; set; } = null!;

    public bool Baja { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual ICollection<EmpresasEspecialidades> EmpresasEspecialidades { get; set; } = new List<EmpresasEspecialidades>();

    public virtual ICollection<EspecialidadesSecciones> EspecialidadesSecciones { get; set; } = new List<EspecialidadesSecciones>();

    public virtual ICollection<TramitesEspecialidades> TramitesEspecialidades { get; set; } = new List<TramitesEspecialidades>();
}
