// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class EstadosEvaluacion
{
    public int IdEstadoEvaluacion { get; set; }

    public string CodigoEstadoEvaluacion { get; set; } = null!;

    public string NombreEstadoEvaluacion { get; set; } = null!;

    public virtual ICollection<TramitesFormulariosEvaluados> TramitesFormulariosEvaluados { get; set; } = new List<TramitesFormulariosEvaluados>();
}
