// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class Files
{
    public int IdFile { get; set; }

    public Guid Rowid { get; set; }

    public byte[] ContentFile { get; set; } = null!;

    public string? FileName { get; set; }

    public string? Extension { get; set; }

    public string? ContentType { get; set; }

    public long Size { get; set; }

    public string? Md5 { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? UpdateDate { get; set; }

    public string? UpdateUser { get; set; }

    public virtual ICollection<EmpresasAntecedentes> EmpresasAntecedentes { get; set; } = new List<EmpresasAntecedentes>();

    public virtual ICollection<EmpresasBienesRaices> EmpresasBienesRaicesIdFileCertificadoContableNavigation { get; set; } = new List<EmpresasBienesRaices>();

    public virtual ICollection<EmpresasBienesRaices> EmpresasBienesRaicesIdFileDetalleInmuebleNavigation { get; set; } = new List<EmpresasBienesRaices>();

    public virtual ICollection<EmpresasEquipos> EmpresasEquiposIdFileCertificadoContableNavigation { get; set; } = new List<EmpresasEquipos>();

    public virtual ICollection<EmpresasEquipos> EmpresasEquiposIdFileDetalleEquipoNavigation { get; set; } = new List<EmpresasEquipos>();

    public virtual ICollection<EmpresasEquipos> EmpresasEquiposIdFileDocumentacionEquipoNavigation { get; set; } = new List<EmpresasEquipos>();

    public virtual ICollection<EmpresasInfDocumentos> EmpresasInfDocumentos { get; set; } = new List<EmpresasInfDocumentos>();

    public virtual ICollection<EmpresasInf> EmpresasInfIdFileConstanciaBcraNavigation { get; set; } = new List<EmpresasInf>();

    public virtual ICollection<EmpresasInf> EmpresasInfIdFileConstanciaInscImpNacionalesNavigation { get; set; } = new List<EmpresasInf>();

    public virtual ICollection<EmpresasObras> EmpresasObras { get; set; } = new List<EmpresasObras>();

    public virtual ICollection<EmpresasObrasEjecucion> EmpresasObrasEjecucion { get; set; } = new List<EmpresasObrasEjecucion>();

    public virtual ICollection<EmpresasRepresentantesTecnicosDesvinculaciones> EmpresasRepresentantesTecnicosDesvinculacionesIdFileBoletaNavigation { get; set; } = new List<EmpresasRepresentantesTecnicosDesvinculaciones>();

    public virtual ICollection<EmpresasRepresentantesTecnicosDesvinculaciones> EmpresasRepresentantesTecnicosDesvinculacionesIdFileContratoNavigation { get; set; } = new List<EmpresasRepresentantesTecnicosDesvinculaciones>();

    public virtual ICollection<EmpresasRepresentantesTecnicosDesvinculaciones> EmpresasRepresentantesTecnicosDesvinculacionesIdFileDesvinculacionNavigation { get; set; } = new List<EmpresasRepresentantesTecnicosDesvinculaciones>();

    public virtual ICollection<EmpresasRepresentantesTecnicosDesvinculaciones> EmpresasRepresentantesTecnicosDesvinculacionesIdFileMatriculaNavigation { get; set; } = new List<EmpresasRepresentantesTecnicosDesvinculaciones>();

    public virtual ICollection<EmpresasRepresentantesTecnicos> EmpresasRepresentantesTecnicosIdFileBoletaNavigation { get; set; } = new List<EmpresasRepresentantesTecnicos>();

    public virtual ICollection<EmpresasRepresentantesTecnicos> EmpresasRepresentantesTecnicosIdFileContratoNavigation { get; set; } = new List<EmpresasRepresentantesTecnicos>();

    public virtual ICollection<EmpresasRepresentantesTecnicos> EmpresasRepresentantesTecnicosIdFileMatriculaNavigation { get; set; } = new List<EmpresasRepresentantesTecnicos>();

    public virtual ICollection<EmpresasSanciones> EmpresasSanciones { get; set; } = new List<EmpresasSanciones>();

    public virtual ICollection<ObrasProvinciaLaPampa> ObrasProvinciaLaPampa { get; set; } = new List<ObrasProvinciaLaPampa>();

    public virtual ICollection<TramitesAntecedentes> TramitesAntecedentes { get; set; } = new List<TramitesAntecedentes>();

    public virtual ICollection<TramitesBienesRaices> TramitesBienesRaicesIdFileCertificadoContableNavigation { get; set; } = new List<TramitesBienesRaices>();

    public virtual ICollection<TramitesBienesRaices> TramitesBienesRaicesIdFileDetalleInmuebleNavigation { get; set; } = new List<TramitesBienesRaices>();

    public virtual ICollection<TramitesEquipos> TramitesEquiposIdFileCertificadoContableNavigation { get; set; } = new List<TramitesEquipos>();

    public virtual ICollection<TramitesEquipos> TramitesEquiposIdFileDetalleEquipoNavigation { get; set; } = new List<TramitesEquipos>();

    public virtual ICollection<TramitesEquipos> TramitesEquiposIdFileDocumentacionEquipoNavigation { get; set; } = new List<TramitesEquipos>();

    public virtual ICollection<Tramites> TramitesIdFileBoletaNavigation { get; set; } = new List<Tramites>();

    public virtual ICollection<Tramites> TramitesIdFileCumplimientoFiscalNavigation { get; set; } = new List<Tramites>();

    public virtual ICollection<Tramites> TramitesIdFileGedoNavigation { get; set; } = new List<Tramites>();

    public virtual ICollection<TramitesInfEmpConsDocumentos> TramitesInfEmpConsDocumentos { get; set; } = new List<TramitesInfEmpConsDocumentos>();

    public virtual ICollection<TramitesInfEmpCons> TramitesInfEmpConsIdFileActaDesignacionNavigation { get; set; } = new List<TramitesInfEmpCons>();

    public virtual ICollection<TramitesInfEmpCons> TramitesInfEmpConsIdFileConstanciaBcraNavigation { get; set; } = new List<TramitesInfEmpCons>();

    public virtual ICollection<TramitesInfEmpCons> TramitesInfEmpConsIdFileContratoNavigation { get; set; } = new List<TramitesInfEmpCons>();

    public virtual ICollection<TramitesInfEmpCons> TramitesInfEmpConsIdFileEstatutoNavigation { get; set; } = new List<TramitesInfEmpCons>();

    public virtual ICollection<TramitesInfEmpCons> TramitesInfEmpConsIdFileRegComercioNavigation { get; set; } = new List<TramitesInfEmpCons>();

    public virtual ICollection<TramitesInfEmpDocumentos> TramitesInfEmpDocumentos { get; set; } = new List<TramitesInfEmpDocumentos>();

    public virtual ICollection<TramitesInfEmp> TramitesInfEmpIdFileConstanciaBcraNavigation { get; set; } = new List<TramitesInfEmp>();

    public virtual ICollection<TramitesInfEmp> TramitesInfEmpIdFileConstanciaInscImpNacionalesNavigation { get; set; } = new List<TramitesInfEmp>();

    public virtual ICollection<TramitesObras> TramitesObras { get; set; } = new List<TramitesObras>();

    public virtual ICollection<TramitesObrasEjecucion> TramitesObrasEjecucion { get; set; } = new List<TramitesObrasEjecucion>();

    public virtual ICollection<TramitesRepresentantesTecnicosDesvinculaciones> TramitesRepresentantesTecnicosDesvinculaciones { get; set; } = new List<TramitesRepresentantesTecnicosDesvinculaciones>();

    public virtual ICollection<TramitesRepresentantesTecnicos> TramitesRepresentantesTecnicosIdFileBoletaNavigation { get; set; } = new List<TramitesRepresentantesTecnicos>();

    public virtual ICollection<TramitesRepresentantesTecnicos> TramitesRepresentantesTecnicosIdFileContratoNavigation { get; set; } = new List<TramitesRepresentantesTecnicos>();

    public virtual ICollection<TramitesRepresentantesTecnicos> TramitesRepresentantesTecnicosIdFileCurriculumNavigation { get; set; } = new List<TramitesRepresentantesTecnicos>();
}
