// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DataAccess.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataAccess.Entities
{
    public partial class GLPContext
    {
        private IGLPContextProcedures? _procedures;

        public virtual IGLPContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new GLPContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IGLPContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class GLPContextProcedures : IGLPContextProcedures
    {
        private readonly GLPContext _context;

        public GLPContextProcedures(GLPContext context)
        {
            _context = context;
        }

        public virtual async Task<int> get_ExpedientesMopAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[get_ExpedientesMop]", sqlParameters, cancellationToken ?? CancellationToken.None);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
