// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DataAccess.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataAccess.Entities
{
    public partial interface IGLPContextProcedures
    {
        Task<int> get_ExpedientesMopAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
