// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class IndicesBancoCentral
{
    public int IdIndiceBcra { get; set; }

    public int IdSituacionBcra { get; set; }

    public decimal MinimoDeudaAdmisible { get; set; }

    public decimal MaximoDeudaAdmisible { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual SituacionesBcra IdSituacionBcraNavigation { get; set; } = null!;
}
