// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class IndicesCostoConstruccion
{
    public int IdIcc { get; set; }

    public int Mes { get; set; }

    public int Anio { get; set; }

    public decimal Valor { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;
}
