// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class LogLoginSuu
{
    public string Username { get; set; } = null!;

    public string? AccessToken { get; set; }

    public string? State { get; set; }

    public DateTime LastUpdateDate { get; set; }
}
