// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class MatrizObrasEnEjecucion
{
    public int IdMatrizObrasEjec { get; set; }

    public decimal PorcCertifificadoDesde { get; set; }

    public decimal PorcCertifificadoHasta { get; set; }

    public decimal Tiempo0 { get; set; }

    public decimal Tiempo10 { get; set; }

    public decimal Tiempo20 { get; set; }

    public decimal Tiempo30 { get; set; }

    public decimal Tiempo40 { get; set; }

    public decimal Tiempo50 { get; set; }

    public decimal Tiempo60 { get; set; }

    public decimal Tiempo70 { get; set; }

    public decimal Tiempo80 { get; set; }

    public decimal Tiempo90 { get; set; }

    public decimal Tiempo100 { get; set; }
}
