// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class MenuesPermisos
{
    public int IdMenuPermiso { get; set; }

    public int IdMenu { get; set; }

    public int? IdPermiso { get; set; }

    public virtual Menues IdMenuNavigation { get; set; } = null!;

    public virtual Permisos? IdPermisoNavigation { get; set; }
}
