// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class Menues
{
    public int IdMenu { get; set; }

    public string Descripcion { get; set; } = null!;

    public string? Aclaraciones { get; set; }

    public string? IconCss { get; set; }

    public string Url { get; set; } = null!;

    public int? IdMenuPadre { get; set; }

    public int? Orden { get; set; }

    public bool Visible { get; set; }

    public string? TituloHijos { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual Menues? IdMenuPadreNavigation { get; set; }

    public virtual ICollection<Menues> InverseIdMenuPadreNavigation { get; set; } = new List<Menues>();

    public virtual ICollection<MenuesPermisos> MenuesPermisos { get; set; } = new List<MenuesPermisos>();
}
