// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class ObrasProvinciaLaPampa
{
    public int IdObraPciaLp { get; set; }

    public string? Expediente { get; set; }

    public string ObraNombre { get; set; } = null!;

    public string? EstadoObra { get; set; }

    public int? PlazoObra { get; set; }

    public decimal? MontoObra { get; set; }

    public DateTime? FechaFinObra { get; set; }

    public decimal? MontoDolaresObra { get; set; }

    public string? Empresa { get; set; }

    public string? CuitEmpresa { get; set; }

    public bool? EsUte { get; set; }

    public decimal? PorcentajeParticipacion { get; set; }

    public int? AnioAvanceObra { get; set; }

    public string? MesAvanceObra { get; set; }

    public decimal? PorcentajeAvanceObra { get; set; }

    public string? Licitante { get; set; }

    public bool? EsAltaPorProceso { get; set; }

    public bool EsAltaPorUsuario { get; set; }

    public bool BajaLogica { get; set; }

    public decimal? CoeficienteConceptual { get; set; }

    public DateTime? FechaInformeCoeficiente { get; set; }

    public int? IdFileInformeCoeficiente { get; set; }

    public DateTime CreateDate { get; set; }

    public string? CreateUser { get; set; }

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual ICollection<EmpresasAntecedentes> EmpresasAntecedentes { get; set; } = new List<EmpresasAntecedentes>();

    public virtual ICollection<EmpresasDetalleObrasEjecucion> EmpresasDetalleObrasEjecucion { get; set; } = new List<EmpresasDetalleObrasEjecucion>();

    public virtual ICollection<EmpresasObras> EmpresasObras { get; set; } = new List<EmpresasObras>();

    public virtual ICollection<EmpresasObrasEjecucion> EmpresasObrasEjecucion { get; set; } = new List<EmpresasObrasEjecucion>();

    public virtual Files? IdFileInformeCoeficienteNavigation { get; set; }

    public virtual ICollection<Tramites> Tramites { get; set; } = new List<Tramites>();

    public virtual ICollection<TramitesAntecedentes> TramitesAntecedentes { get; set; } = new List<TramitesAntecedentes>();

    public virtual ICollection<TramitesBalancesGeneralesEvaluarDetalleObrasEjecucion> TramitesBalancesGeneralesEvaluarDetalleObrasEjecucion { get; set; } = new List<TramitesBalancesGeneralesEvaluarDetalleObrasEjecucion>();

    public virtual ICollection<TramitesObras> TramitesObras { get; set; } = new List<TramitesObras>();

    public virtual ICollection<TramitesObrasEjecucion> TramitesObrasEjecucion { get; set; } = new List<TramitesObrasEjecucion>();
}
