// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class ObrasProvinciaLaPampaProcessInfo
{
    public DateTime UltimaFechaActualizacion { get; set; }
}
