// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class Parametros
{
    public int IdParametro { get; set; }

    public string CodigoParametro { get; set; } = null!;

    public string NombreParametro { get; set; } = null!;

    public string? ValorChar { get; set; }

    public decimal? ValorNum { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }
}
