// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class Perfiles
{
    public int IdPerfil { get; set; }

    public string Nombre { get; set; } = null!;

    public virtual ICollection<PerfilesPermisos> PerfilesPermisos { get; set; } = new List<PerfilesPermisos>();

    public virtual ICollection<RelUsuariosPerfiles> RelUsuariosPerfiles { get; set; } = new List<RelUsuariosPerfiles>();
}
