// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class PerfilesPermisos
{
    public int IdPerfilPermiso { get; set; }

    public int IdPerfil { get; set; }

    public int IdPermiso { get; set; }

    public virtual Perfiles IdPerfilNavigation { get; set; } = null!;

    public virtual Permisos IdPermisoNavigation { get; set; } = null!;
}
