// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class Permisos
{
    public int IdPermiso { get; set; }

    public string Codigo { get; set; } = null!;

    public string Nombre { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public virtual ICollection<MenuesPermisos> MenuesPermisos { get; set; } = new List<MenuesPermisos>();

    public virtual ICollection<PerfilesPermisos> PerfilesPermisos { get; set; } = new List<PerfilesPermisos>();
}
