// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class Provincias
{
    public int IdProvincia { get; set; }

    public string Descripcion { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public virtual ICollection<EmpresasRepresentantesTecnicosJurisdicciones> EmpresasRepresentantesTecnicosJurisdicciones { get; set; } = new List<EmpresasRepresentantesTecnicosJurisdicciones>();

    public virtual ICollection<TramitesRepresentantesTecnicosJurisdicciones> TramitesRepresentantesTecnicosJurisdicciones { get; set; } = new List<TramitesRepresentantesTecnicosJurisdicciones>();
}
