// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class RelUsuariosPerfiles
{
    public int IdUsuarioPerfil { get; set; }

    public string Userid { get; set; } = null!;

    public int IdPerfil { get; set; }

    public virtual Perfiles IdPerfilNavigation { get; set; } = null!;
}
