// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class SituacionesBcra
{
    public int IdsituacionBcra { get; set; }

    public string Nombre { get; set; } = null!;

    public virtual ICollection<IndicesBancoCentral> IndicesBancoCentral { get; set; } = new List<IndicesBancoCentral>();
}
