// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TiposDeTramite
{
    public int IdTipoTramite { get; set; }

    public string Descripcion { get; set; } = null!;

    public int IdGrupoTramite { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual ICollection<Tramites> Tramites { get; set; } = new List<Tramites>();
}
