// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TiposDeObras
{
    public int IdTipoObra { get; set; }

    public string Nombre { get; set; } = null!;

    public decimal Coeficiente { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual ICollection<EmpresasObras> EmpresasObras { get; set; } = new List<EmpresasObras>();

    public virtual ICollection<EmpresasObrasEjecucion> EmpresasObrasEjecucion { get; set; } = new List<EmpresasObrasEjecucion>();

    public virtual ICollection<TramitesObras> TramitesObras { get; set; } = new List<TramitesObras>();

    public virtual ICollection<TramitesObrasEjecucion> TramitesObrasEjecucion { get; set; } = new List<TramitesObrasEjecucion>();
}
