// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TiposDeCaracterLegal
{
    public int IdTipoCaracter { get; set; }

    public string Descripcion { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public virtual ICollection<TramitesInfEmpConsPersonas> TramitesInfEmpConsPersonas { get; set; } = new List<TramitesInfEmpConsPersonas>();
}
