// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TiposDeDocumentos
{
    public int IdTipoDocumento { get; set; }

    public int IdGrupoTramite { get; set; }

    public string Descripcion { get; set; } = null!;

    public int? TamanioMaximoMb { get; set; }

    public string Extension { get; set; } = null!;

    public string? AcronimoGde { get; set; }

    public bool Obligatorio { get; set; }

    public bool SePermiteVariasVeces { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual ICollection<EmpresasInfDocumentos> EmpresasInfDocumentos { get; set; } = new List<EmpresasInfDocumentos>();

    public virtual ICollection<TramitesInfEmpConsDocumentos> TramitesInfEmpConsDocumentos { get; set; } = new List<TramitesInfEmpConsDocumentos>();

    public virtual ICollection<TramitesInfEmpDocumentos> TramitesInfEmpDocumentos { get; set; } = new List<TramitesInfEmpDocumentos>();
}
