// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TiposDeSociedad
{
    public int IdTipoSociedad { get; set; }

    public string Descripcion { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public virtual ICollection<TramitesInfEmpCons> TramitesInfEmpCons { get; set; } = new List<TramitesInfEmpCons>();
}
