// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesAntecedentesDdjjmensual
{
    public int IdTramiteAntecedenteDdjjmensual { get; set; }

    public int IdTramiteAntecedente { get; set; }

    public int Mes { get; set; }

    public int Anio { get; set; }

    public decimal Monto { get; set; }

    public virtual TramitesAntecedentes IdTramiteAntecedenteNavigation { get; set; } = null!;
}
