// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesBalancesGeneralesEvaluarCapProd
{
    public int IdTramiteBalanceGeneralEvaluarCp { get; set; }

    public int IdTramiteBalanceGeneralEvaluar { get; set; }

    public int? IdSeccion { get; set; }

    public string? DescripcionSeccion { get; set; }

    public decimal? Importe { get; set; }

    public decimal? CoefCapacTecnicaxEquipo { get; set; }

    public decimal? MultiplicadorCapEconomica { get; set; }

    public decimal? ImporteResultante { get; set; }

    public virtual EspecialidadesSecciones? IdSeccionNavigation { get; set; }

    public virtual TramitesBalancesGeneralesEvaluar IdTramiteBalanceGeneralEvaluarNavigation { get; set; } = null!;
}
