// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesInfEmpConsPersonas
{
    public int IdPersona { get; set; }

    public int IdTramiteInfEmpCon { get; set; }

    public string Apellidos { get; set; } = null!;

    public string Nombres { get; set; } = null!;

    public int IdTipoCaracterLegal { get; set; }

    public int NroDni { get; set; }

    public virtual TiposDeCaracterLegal IdTipoCaracterLegalNavigation { get; set; } = null!;

    public virtual TramitesInfEmpCons IdTramiteInfEmpConNavigation { get; set; } = null!;
}
