// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesHistorialEstados
{
    public int IdTramiteHist { get; set; }

    public int IdTramite { get; set; }

    public string CodEstadoAnterior { get; set; } = null!;

    public string CodEstadoNuevo { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual Tramites IdTramiteNavigation { get; set; } = null!;
}
