// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesInfEmp
{
    public int IdTramiteInfEmp { get; set; }

    public int IdTramite { get; set; }

    public DateTime FechaInicioActividades { get; set; }

    public int? IdFileConstanciaInscImpNacionales { get; set; }

    public string? FilenameConstanciaInscImpNacionales { get; set; }

    public int? IdFileConstanciaBcra { get; set; }

    public string? FilenameConstanciaBcra { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastupdateUser { get; set; }

    public virtual Files? IdFileConstanciaBcraNavigation { get; set; }

    public virtual Files? IdFileConstanciaInscImpNacionalesNavigation { get; set; }

    public virtual Tramites IdTramiteNavigation { get; set; } = null!;

    public virtual ICollection<TramitesInfEmpDeudas> TramitesInfEmpDeudas { get; set; } = new List<TramitesInfEmpDeudas>();

    public virtual ICollection<TramitesInfEmpDocumentos> TramitesInfEmpDocumentos { get; set; } = new List<TramitesInfEmpDocumentos>();
}
