// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesInfEmpConsDocumentos
{
    public int IdTramiteInfEmpConsDocumento { get; set; }

    public int IdTramiteInfEmpCons { get; set; }

    public int IdTipoDocumento { get; set; }

    public int IdFile { get; set; }

    public string Filename { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual Files IdFileNavigation { get; set; } = null!;

    public virtual TiposDeDocumentos IdTipoDocumentoNavigation { get; set; } = null!;

    public virtual TramitesInfEmpCons IdTramiteInfEmpConsNavigation { get; set; } = null!;
}
