// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesEstados
{
    public int IdEstado { get; set; }

    public string CodEstado { get; set; } = null!;

    public string NombreEstado { get; set; } = null!;

    public virtual ICollection<Tramites> Tramites { get; set; } = new List<Tramites>();
}
