// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesRepresentantesTecnicosEspecialidades
{
    public int IdRepresentanteEspecialidad { get; set; }

    public int IdRepresentanteTecnico { get; set; }

    public int IdTramiteEspecialidad { get; set; }

    public virtual TramitesRepresentantesTecnicos IdRepresentanteTecnicoNavigation { get; set; } = null!;

    public virtual TramitesEspecialidades IdTramiteEspecialidadNavigation { get; set; } = null!;
}
