// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesEspecialidadesEquipos
{
    public int IdTramiteEspecialidadEquipo { get; set; }

    public int IdTramiteEspecialidadTarea { get; set; }

    public int IdEquipo { get; set; }

    public virtual EspecialidadesEquipos IdEquipoNavigation { get; set; } = null!;

    public virtual TramitesEspecialidadesTareas IdTramiteEspecialidadTareaNavigation { get; set; } = null!;
}
