// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesEspecialidadesTareas
{
    public int IdTramiteEspecialidadTarea { get; set; }

    public int? IdTramiteEspecialidadSeccion { get; set; }

    public int IdTarea { get; set; }

    public virtual EspecialidadesTareas IdTareaNavigation { get; set; } = null!;

    public virtual TramitesEspecialidadesSecciones? IdTramiteEspecialidadSeccionNavigation { get; set; }

    public virtual ICollection<TramitesEspecialidadesEquipos> TramitesEspecialidadesEquipos { get; set; } = new List<TramitesEspecialidadesEquipos>();
}
