// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class Tramites
{
    public int IdTramite { get; set; }

    public string IdentificadorUnico { get; set; } = null!;

    public int? IdTipoTramite { get; set; }

    public int IdEmpresa { get; set; }

    public int IdEstado { get; set; }

    public int? NroBoleta { get; set; }

    public int? IdFileBoleta { get; set; }

    public string? FilenameBoleta { get; set; }

    public int? IdFileCumplimientoFiscal { get; set; }

    public string? FilenameCumplimientoFiscal { get; set; }

    public string? UsuarioAsignado { get; set; }

    public DateTime? FechaAsignacion { get; set; }

    public bool SinDatosForm8 { get; set; }

    public bool SinDatosForm10 { get; set; }

    public bool SinDatosForm11 { get; set; }

    public bool SinDatosForm12 { get; set; }

    public string? NumeroGedo { get; set; }

    public int? IdFileGedo { get; set; }

    public int? IdObraPciaLp { get; set; }

    public DateTime? FechaVencimiento { get; set; }

    public int? IdTramiteOrigen { get; set; }

    public bool SePresentaEnUte { get; set; }

    public decimal? PorcParticipUte { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual ICollection<Empresas> EmpresasIdTramiteOrigenNavigation { get; set; } = new List<Empresas>();

    public virtual ICollection<Empresas> EmpresasIdTramiteOrigenRecoNavigation { get; set; } = new List<Empresas>();

    public virtual Empresas IdEmpresaNavigation { get; set; } = null!;

    public virtual TramitesEstados IdEstadoNavigation { get; set; } = null!;

    public virtual Files? IdFileBoletaNavigation { get; set; }

    public virtual Files? IdFileCumplimientoFiscalNavigation { get; set; }

    public virtual Files? IdFileGedoNavigation { get; set; }

    public virtual ObrasProvinciaLaPampa? IdObraPciaLpNavigation { get; set; }

    public virtual TiposDeTramite? IdTipoTramiteNavigation { get; set; }

    public virtual Tramites? IdTramiteOrigenNavigation { get; set; }

    public virtual ICollection<Tramites> InverseIdTramiteOrigenNavigation { get; set; } = new List<Tramites>();

    public virtual ICollection<TramitesAntecedentes> TramitesAntecedentes { get; set; } = new List<TramitesAntecedentes>();

    public virtual ICollection<TramitesBalancesGenerales> TramitesBalancesGenerales { get; set; } = new List<TramitesBalancesGenerales>();

    public virtual ICollection<TramitesBienesRaices> TramitesBienesRaices { get; set; } = new List<TramitesBienesRaices>();

    public virtual ICollection<TramitesEquipos> TramitesEquipos { get; set; } = new List<TramitesEquipos>();

    public virtual ICollection<TramitesEspecialidades> TramitesEspecialidades { get; set; } = new List<TramitesEspecialidades>();

    public virtual ICollection<TramitesFormulariosEvaluados> TramitesFormulariosEvaluados { get; set; } = new List<TramitesFormulariosEvaluados>();

    public virtual ICollection<TramitesHistorialEstados> TramitesHistorialEstados { get; set; } = new List<TramitesHistorialEstados>();

    public virtual TramitesInfEmp? TramitesInfEmp { get; set; }

    public virtual TramitesInfEmpCons? TramitesInfEmpCons { get; set; }

    public virtual ICollection<TramitesNotificaciones> TramitesNotificaciones { get; set; } = new List<TramitesNotificaciones>();

    public virtual ICollection<TramitesObras> TramitesObras { get; set; } = new List<TramitesObras>();

    public virtual ICollection<TramitesObrasEjecucion> TramitesObrasEjecucion { get; set; } = new List<TramitesObrasEjecucion>();

    public virtual ICollection<TramitesRepresentantesTecnicos> TramitesRepresentantesTecnicos { get; set; } = new List<TramitesRepresentantesTecnicos>();
}
