// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesInfEmpDeudas
{
    public int IdTramiteInfEmpDeuda { get; set; }

    public int IdTramiteInfEmp { get; set; }

    public string Entidad { get; set; } = null!;

    public string Periodo { get; set; } = null!;

    public int Situacion { get; set; }

    public decimal Monto { get; set; }

    public int DiasDeAtraso { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual TramitesInfEmp IdTramiteInfEmpNavigation { get; set; } = null!;
}
