// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesRepresentantesTecnicos
{
    public int IdRepresentanteTecnico { get; set; }

    public int IdTramite { get; set; }

    public string Apellido { get; set; } = null!;

    public string Nombres { get; set; } = null!;

    public decimal Cuit { get; set; }

    public string Cargo { get; set; } = null!;

    public string Matricula { get; set; } = null!;

    public DateTime FechaVencimientoMatricula { get; set; }

    public DateTime FechaVencimientoContrato { get; set; }

    public int IdFileContrato { get; set; }

    public string FilenameContrato { get; set; } = null!;

    public int IdFileBoleta { get; set; }

    public string FilenameBoleta { get; set; } = null!;

    public int IdFileMatricula { get; set; }

    public string FilenameMatricula { get; set; } = null!;

    public int? IdFileCurriculum { get; set; }

    public string? FilenameCurriculum { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual Files IdFileBoletaNavigation { get; set; } = null!;

    public virtual Files IdFileContratoNavigation { get; set; } = null!;

    public virtual Files? IdFileCurriculumNavigation { get; set; }

    public virtual Tramites IdTramiteNavigation { get; set; } = null!;

    public virtual TramitesRepresentantesTecnicosDesvinculaciones? TramitesRepresentantesTecnicosDesvinculaciones { get; set; }

    public virtual ICollection<TramitesRepresentantesTecnicosEspecialidades> TramitesRepresentantesTecnicosEspecialidades { get; set; } = new List<TramitesRepresentantesTecnicosEspecialidades>();

    public virtual ICollection<TramitesRepresentantesTecnicosJurisdicciones> TramitesRepresentantesTecnicosJurisdicciones { get; set; } = new List<TramitesRepresentantesTecnicosJurisdicciones>();
}
