// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesBalancesGeneralesEvaluarCapTecnica
{
    public int IdTramiteBalanceGeneralEvaluarCt { get; set; }

    public int IdTramiteBalanceGeneralEvaluar { get; set; }

    public int? IdSeccion { get; set; }

    public string? DescripcionSeccion { get; set; }

    public decimal? Monto { get; set; }

    public int? Mes { get; set; }

    public int? Anio { get; set; }

    public decimal? CoefActualizacion { get; set; }

    public decimal? CoefTipoObra { get; set; }

    public decimal? CapacidadTecnicaxEquipo { get; set; }

    public decimal? CoerficienteConceptual { get; set; }

    public decimal? CapacidadTecnicaFinal { get; set; }

    public virtual EspecialidadesSecciones? IdSeccionNavigation { get; set; }

    public virtual TramitesBalancesGeneralesEvaluar IdTramiteBalanceGeneralEvaluarNavigation { get; set; } = null!;
}
