// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesEspecialidades
{
    public int IdTramiteEspecialidad { get; set; }

    public int IdTramite { get; set; }

    public int IdEspecialidad { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual Especialidades IdEspecialidadNavigation { get; set; } = null!;

    public virtual Tramites IdTramiteNavigation { get; set; } = null!;

    public virtual ICollection<TramitesAntecedentes> TramitesAntecedentes { get; set; } = new List<TramitesAntecedentes>();

    public virtual ICollection<TramitesEspecialidadesSecciones> TramitesEspecialidadesSecciones { get; set; } = new List<TramitesEspecialidadesSecciones>();

    public virtual ICollection<TramitesObras> TramitesObras { get; set; } = new List<TramitesObras>();

    public virtual ICollection<TramitesRepresentantesTecnicosEspecialidades> TramitesRepresentantesTecnicosEspecialidades { get; set; } = new List<TramitesRepresentantesTecnicosEspecialidades>();
}
