// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesObras
{
    public int IdTramiteObra { get; set; }

    public int IdTramite { get; set; }

    public int IdTramiteEspecialidad { get; set; }

    public int IdTramiteEspecialidadSeccion { get; set; }

    public int IdObraPciaLp { get; set; }

    public string Comitente { get; set; } = null!;

    public int IdTipoObra { get; set; }

    public decimal Monto { get; set; }

    public string PeriodoBase { get; set; } = null!;

    public string PeriodoContrato { get; set; } = null!;

    public string PeriodoFin { get; set; } = null!;

    public int IdFile { get; set; }

    public string Filename { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual Files IdFileNavigation { get; set; } = null!;

    public virtual ObrasProvinciaLaPampa IdObraPciaLpNavigation { get; set; } = null!;

    public virtual TiposDeObras IdTipoObraNavigation { get; set; } = null!;

    public virtual TramitesEspecialidades IdTramiteEspecialidadNavigation { get; set; } = null!;

    public virtual TramitesEspecialidadesSecciones IdTramiteEspecialidadSeccionNavigation { get; set; } = null!;

    public virtual Tramites IdTramiteNavigation { get; set; } = null!;
}
