// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesEquipos
{
    public int IdTramiteEquipo { get; set; }

    public int IdTramite { get; set; }

    public bool Afectado { get; set; }

    public int IdFileDetalleEquipo { get; set; }

    public string FilenameDetalleEquipo { get; set; } = null!;

    public int IdFileCertificadoContable { get; set; }

    public string FilenameCertificadoContable { get; set; } = null!;

    public int? IdFileDocumentacionEquipo { get; set; }

    public string? FilenameDocumentacionEquipo { get; set; }

    public decimal MontoRealizacion { get; set; }

    public decimal? MontoRealizacionEvaluador { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public DateTime? LastUpdateDate { get; set; }

    public virtual Files IdFileCertificadoContableNavigation { get; set; } = null!;

    public virtual Files IdFileDetalleEquipoNavigation { get; set; } = null!;

    public virtual Files? IdFileDocumentacionEquipoNavigation { get; set; }

    public virtual Tramites IdTramiteNavigation { get; set; } = null!;
}
