// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesInfEmpConsDeudas
{
    public int IdTramiteInfEmpConsDeuda { get; set; }

    public int IdTramiteInfEmpCons { get; set; }

    public string Entidad { get; set; } = null!;

    public string Periodo { get; set; } = null!;

    public int Situacion { get; set; }

    public decimal Monto { get; set; }

    public int DiasDeAtraso { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual TramitesInfEmpCons IdTramiteInfEmpConsNavigation { get; set; } = null!;
}
