// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesInfEmpCons
{
    public int IdTramiteInfEmpCon { get; set; }

    public int IdTramite { get; set; }

    public int TipoEmpresa { get; set; }

    public string RazonSocial { get; set; } = null!;

    public int? IdTipoSociedad { get; set; }

    public int? IdFileContrato { get; set; }

    public string? FilenameContrato { get; set; }

    public int? IdFileEstatuto { get; set; }

    public string? FilenameEstatuto { get; set; }

    public string? DeRegComercio { get; set; }

    public DateTime? FechaRegComercio { get; set; }

    public string? LibroRegComercio { get; set; }

    public string? TomoRegComercio { get; set; }

    public string? FolioRegComercio { get; set; }

    public int? IdFileRegComercio { get; set; }

    public string? FilenameRegComercio { get; set; }

    public int? AniosDuracionSoc { get; set; }

    public DateTime? FechaConstitucionSoc { get; set; }

    public DateTime? FechaVencimientoSoc { get; set; }

    public string? ProrrogaDePlazoSoc { get; set; }

    public int? IdFileActaDesignacion { get; set; }

    public string? FilenameActaDesignacion { get; set; }

    public string? Cuit { get; set; }

    public string? NroIibb { get; set; }

    public DateTime? FechaInscripcionIibb { get; set; }

    public int TipoIibb { get; set; }

    public int TipoIva { get; set; }

    public DateTime? FechaInscripcionIva { get; set; }

    public bool EsInscriptoGan { get; set; }

    public DateTime? FechaInscripcionGan { get; set; }

    public string? OtrosImpuestos { get; set; }

    public int? IdFileConstanciaBcra { get; set; }

    public string? FilenameConstanciaBcra { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual Files? IdFileActaDesignacionNavigation { get; set; }

    public virtual Files? IdFileConstanciaBcraNavigation { get; set; }

    public virtual Files? IdFileContratoNavigation { get; set; }

    public virtual Files? IdFileEstatutoNavigation { get; set; }

    public virtual Files? IdFileRegComercioNavigation { get; set; }

    public virtual TiposDeSociedad? IdTipoSociedadNavigation { get; set; }

    public virtual Tramites IdTramiteNavigation { get; set; } = null!;

    public virtual ICollection<TramitesInfEmpConsDeudas> TramitesInfEmpConsDeudas { get; set; } = new List<TramitesInfEmpConsDeudas>();

    public virtual ICollection<TramitesInfEmpConsDocumentos> TramitesInfEmpConsDocumentos { get; set; } = new List<TramitesInfEmpConsDocumentos>();

    public virtual ICollection<TramitesInfEmpConsPersonas> TramitesInfEmpConsPersonas { get; set; } = new List<TramitesInfEmpConsPersonas>();
}
