// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesAntecedentes
{
    public int IdTramiteAntecedente { get; set; }

    public int IdTramite { get; set; }

    public int IdTramiteEspecialidad { get; set; }

    public int IdTramiteEspecialidadSeccion { get; set; }

    public int IdObraPciaLp { get; set; }

    public string Ubicacion { get; set; } = null!;

    public string Comitente { get; set; } = null!;

    public string PeriodoBase { get; set; } = null!;

    public string PeriodoInicio { get; set; } = null!;

    public int Plazo { get; set; }

    public decimal MontoContrato { get; set; }

    public decimal MontoEjecutado { get; set; }

    public decimal MontoAejecutar { get; set; }

    public string RepresentanteTecnico { get; set; } = null!;

    public int IdFile { get; set; }

    public string Filename { get; set; } = null!;

    public string CreateUser { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public DateTime? LastUpdateDate { get; set; }

    public virtual Files IdFileNavigation { get; set; } = null!;

    public virtual ObrasProvinciaLaPampa IdObraPciaLpNavigation { get; set; } = null!;

    public virtual TramitesEspecialidades IdTramiteEspecialidadNavigation { get; set; } = null!;

    public virtual TramitesEspecialidadesSecciones IdTramiteEspecialidadSeccionNavigation { get; set; } = null!;

    public virtual Tramites IdTramiteNavigation { get; set; } = null!;

    public virtual ICollection<TramitesAntecedentesDdjjmensual> TramitesAntecedentesDdjjmensual { get; set; } = new List<TramitesAntecedentesDdjjmensual>();
}
