// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesRepresentantesTecnicosDesvinculaciones
{
    public int IdRepresentanteTecnico { get; set; }

    public int IdFileDesvinculacion { get; set; }

    public string FilenameDesvinculacion { get; set; } = null!;

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public virtual Files IdFileDesvinculacionNavigation { get; set; } = null!;

    public virtual TramitesRepresentantesTecnicos IdRepresentanteTecnicoNavigation { get; set; } = null!;
}
