// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesEspecialidadesSecciones
{
    public int IdTramiteEspecialidadSeccion { get; set; }

    public int IdTramiteEspecialidad { get; set; }

    public int IdSeccion { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual EspecialidadesSecciones IdSeccionNavigation { get; set; } = null!;

    public virtual TramitesEspecialidades IdTramiteEspecialidadNavigation { get; set; } = null!;

    public virtual ICollection<TramitesAntecedentes> TramitesAntecedentes { get; set; } = new List<TramitesAntecedentes>();

    public virtual ICollection<TramitesEspecialidadesTareas> TramitesEspecialidadesTareas { get; set; } = new List<TramitesEspecialidadesTareas>();

    public virtual ICollection<TramitesObras> TramitesObras { get; set; } = new List<TramitesObras>();
}
