// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesFormulariosEvaluados
{
    public int IdTramiteFormEvaluado { get; set; }

    public int IdTramite { get; set; }

    public int NroFormulario { get; set; }

    public int NroNotificacion { get; set; }

    public int IdEstadoEvaluacion { get; set; }

    public string? MensajeNotificacion { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual EstadosEvaluacion IdEstadoEvaluacionNavigation { get; set; } = null!;

    public virtual Tramites IdTramiteNavigation { get; set; } = null!;
}
