// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesBalancesGeneralesEvaluar
{
    public int IdTramiteBalanceGeneralEvaluar { get; set; }

    public int IdTramiteBalanceGeneral { get; set; }

    public decimal CoefObrasOficialesDepositosCortoPlazo { get; set; }

    public decimal CoefObrasOficialesDepositosLargoPlazo { get; set; }

    public decimal CoefObrasOficialesInversionesCortoPlazo { get; set; }

    public decimal CoefObrasOficialesInversionesLargoPlazo { get; set; }

    public decimal CoefObrasOficialesOtrosConceptos { get; set; }

    public decimal CoefObrasParticularesDepositosCortoPlazo { get; set; }

    public decimal CoefObrasParticularesDepositosLargoPlazo { get; set; }

    public decimal CoefObrasParticularesInversionesCortoPlazo { get; set; }

    public decimal CoefObrasParticularesInversionesLargoPlazo { get; set; }

    public decimal CoefObrasParticularesInversiones { get; set; }

    public decimal CoefObrasParticularesOtrosConceptos { get; set; }

    public decimal CoefDisponibilidadesCajaYbancos { get; set; }

    public decimal CoefBienesDeUsoInversiones { get; set; }

    public decimal CoefBienesDeUsoEquiposAfectados { get; set; }

    public decimal CoefBienesDeUsoEquiposNoAfectados { get; set; }

    public decimal CoefBienesDeUsoInmueblesAfectados { get; set; }

    public decimal CoefBienesDeUsoInmueblesNoAfectados { get; set; }

    public decimal CoefBienesDeUsoOtrosConceptos { get; set; }

    public decimal CoefBienesDeCambioMaterialesEnDeposito { get; set; }

    public decimal CoefBienesDeCambioOtrosConceptos { get; set; }

    public decimal CoefDeudasCortoPlazo { get; set; }

    public decimal CoefDeudasLargoPlazo { get; set; }

    public decimal CoefCapacidadEconomicaArqRep { get; set; }

    public decimal CoefCapacidadEconomicaByC { get; set; }

    public decimal CoefCapacidadEconomicaAyC { get; set; }

    public decimal CapitalRealEspecifico { get; set; }

    public decimal CapitalRealEspecificoEvaluar { get; set; }

    public decimal CapacidadEconomicaArqRep { get; set; }

    public decimal CapacidadEconomicaByC { get; set; }

    public decimal CapacidadEconomicaAyC { get; set; }

    public int EstadoDeudaBcra { get; set; }

    public decimal CoeficienteEstadoDeudaBcra { get; set; }

    public decimal TotalEquiposAfecEvaluar { get; set; }

    public decimal TotalEquiposNoAfecEvaluar { get; set; }

    public decimal TotalInmueblesAfecEvaluar { get; set; }

    public decimal TotalInmueblesNoAfecEvaluar { get; set; }

    public decimal IndiceSolvencia { get; set; }

    public decimal IndiceLiquidez { get; set; }

    public decimal IndiceSolvenciaResultante { get; set; }

    public decimal IndiceLiquidezResultante { get; set; }

    public decimal IndiceAntiguedadEmpresa { get; set; }

    public decimal IndiceRelacionEquipos { get; set; }

    public decimal IndiceRelacionEquiposResultante { get; set; }

    public decimal Factor { get; set; }

    public decimal TotalContratadoObrasEjecucion { get; set; }

    public decimal IndiceUvi { get; set; }

    public decimal CoeficienteConceptual { get; set; }

    public int AniosAntiguedadEmpresa { get; set; }

    public DateTime CreateDate { get; set; }

    public string CreateUser { get; set; } = null!;

    public DateTime? LastUpdateDate { get; set; }

    public string? LastUpdateUser { get; set; }

    public virtual TramitesBalancesGenerales IdTramiteBalanceGeneralNavigation { get; set; } = null!;

    public virtual ICollection<TramitesBalancesGeneralesEvaluarCapEjec> TramitesBalancesGeneralesEvaluarCapEjec { get; set; } = new List<TramitesBalancesGeneralesEvaluarCapEjec>();

    public virtual ICollection<TramitesBalancesGeneralesEvaluarCapProd> TramitesBalancesGeneralesEvaluarCapProd { get; set; } = new List<TramitesBalancesGeneralesEvaluarCapProd>();

    public virtual ICollection<TramitesBalancesGeneralesEvaluarCapTecnica> TramitesBalancesGeneralesEvaluarCapTecnica { get; set; } = new List<TramitesBalancesGeneralesEvaluarCapTecnica>();

    public virtual ICollection<TramitesBalancesGeneralesEvaluarCapTecxEquipo> TramitesBalancesGeneralesEvaluarCapTecxEquipo { get; set; } = new List<TramitesBalancesGeneralesEvaluarCapTecxEquipo>();

    public virtual ICollection<TramitesBalancesGeneralesEvaluarConstanciaCap> TramitesBalancesGeneralesEvaluarConstanciaCap { get; set; } = new List<TramitesBalancesGeneralesEvaluarConstanciaCap>();

    public virtual ICollection<TramitesBalancesGeneralesEvaluarDetalleObrasEjecucion> TramitesBalancesGeneralesEvaluarDetalleObrasEjecucion { get; set; } = new List<TramitesBalancesGeneralesEvaluarDetalleObrasEjecucion>();
}
