// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesBalancesGeneralesEvaluarConstanciaCap
{
    public int IdTramiteBalanceGeneralEvaluarCc { get; set; }

    public int IdTramiteBalanceGeneralEvaluar { get; set; }

    public int? IdSeccion { get; set; }

    public string? DescripcionSeccion { get; set; }

    public decimal? CapacidadTecnica { get; set; }

    public decimal? CapacidadTecnicaUvi { get; set; }

    public decimal? CapacidadContratacion { get; set; }

    public decimal? CapacidadContratacionUvi { get; set; }

    public decimal? EjecucaionAnual { get; set; }

    public decimal? EjecucaionAnualUvi { get; set; }

    public virtual EspecialidadesSecciones? IdSeccionNavigation { get; set; }

    public virtual TramitesBalancesGeneralesEvaluar IdTramiteBalanceGeneralEvaluarNavigation { get; set; } = null!;
}
