// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>
#nullable enable

using System;
using System.Collections.Generic;

namespace DataAccess.Entities;

public partial class TramitesRepresentantesTecnicosJurisdicciones
{
    public int IdRepresentanteTecnicoJurisdiccion { get; set; }

    public int IdRepresentanteTecnico { get; set; }

    public int IdProvincia { get; set; }

    public virtual Provincias IdProvinciaNavigation { get; set; } = null!;

    public virtual TramitesRepresentantesTecnicos IdRepresentanteTecnicoNavigation { get; set; } = null!;
}
