//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Gedo.GenerarDocumentoCnn
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class ParametroInvalidoException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class responseExternalGenerarDocumento
    {
        
        private string licenciaField;
        
        private string numeroField;
        
        private string numeroEspecialField;
        
        private string urlArchivoGeneradoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string licencia
        {
            get
            {
                return this.licenciaField;
            }
            set
            {
                this.licenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string numeroEspecial
        {
            get
            {
                return this.numeroEspecialField;
            }
            set
            {
                this.numeroEspecialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string urlArchivoGenerado
        {
            get
            {
                return this.urlArchivoGeneradoField;
            }
            set
            {
                this.urlArchivoGeneradoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class archivoEmbebidoDTO
    {
        
        private byte[] dataArchivoField;
        
        private string nombreArchivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] dataArchivo
        {
            get
            {
                return this.dataArchivoField;
            }
            set
            {
                this.dataArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreArchivo
        {
            get
            {
                return this.nombreArchivoField;
            }
            set
            {
                this.nombreArchivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(requestExternalGenerarDocumentoUsuarioExterno))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(requestExternalGenerarDocumentoVersionado))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class requestExternalGenerarDocumento
    {
        
        private string acronimoTipoDocumentoField;
        
        private byte[] dataField;
        
        private int idTransaccionField;
        
        private bool idTransaccionFieldSpecified;
        
        private archivoEmbebidoDTO[] listaArchivosEmbebidosField;
        
        private string[] listaUsuariosDestinatariosField;
        
        private string[] listaUsuariosDestinatariosCopiaField;
        
        private string[] listaUsuariosDestinatariosCopiaOcultaField;
        
        private requestExternalGenerarDocumentoEntry[] listaUsuariosDestinatariosExternosField;
        
        private string mensajeDestinatarioField;
        
        private requestExternalGenerarDocumentoEntry1[] metaDatosField;
        
        private string referenciaField;
        
        private string sistemaOrigenField;
        
        private string tipoArchivoField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string acronimoTipoDocumento
        {
            get
            {
                return this.acronimoTipoDocumentoField;
            }
            set
            {
                this.acronimoTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTransaccion
        {
            get
            {
                return this.idTransaccionField;
            }
            set
            {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTransaccionSpecified
        {
            get
            {
                return this.idTransaccionFieldSpecified;
            }
            set
            {
                this.idTransaccionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaArchivosEmbebidos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public archivoEmbebidoDTO[] listaArchivosEmbebidos
        {
            get
            {
                return this.listaArchivosEmbebidosField;
            }
            set
            {
                this.listaArchivosEmbebidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaUsuariosDestinatarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string[] listaUsuariosDestinatarios
        {
            get
            {
                return this.listaUsuariosDestinatariosField;
            }
            set
            {
                this.listaUsuariosDestinatariosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaUsuariosDestinatariosCopia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string[] listaUsuariosDestinatariosCopia
        {
            get
            {
                return this.listaUsuariosDestinatariosCopiaField;
            }
            set
            {
                this.listaUsuariosDestinatariosCopiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaUsuariosDestinatariosCopiaOculta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string[] listaUsuariosDestinatariosCopiaOculta
        {
            get
            {
                return this.listaUsuariosDestinatariosCopiaOcultaField;
            }
            set
            {
                this.listaUsuariosDestinatariosCopiaOcultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public requestExternalGenerarDocumentoEntry[] listaUsuariosDestinatariosExternos
        {
            get
            {
                return this.listaUsuariosDestinatariosExternosField;
            }
            set
            {
                this.listaUsuariosDestinatariosExternosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string mensajeDestinatario
        {
            get
            {
                return this.mensajeDestinatarioField;
            }
            set
            {
                this.mensajeDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public requestExternalGenerarDocumentoEntry1[] metaDatos
        {
            get
            {
                return this.metaDatosField;
            }
            set
            {
                this.metaDatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string sistemaOrigen
        {
            get
            {
                return this.sistemaOrigenField;
            }
            set
            {
                this.sistemaOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string tipoArchivo
        {
            get
            {
                return this.tipoArchivoField;
            }
            set
            {
                this.tipoArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class requestExternalGenerarDocumentoEntry
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class requestExternalGenerarDocumentoEntry1
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class requestExternalGenerarDocumentoUsuarioExterno : requestExternalGenerarDocumento
    {
        
        private string cargoField;
        
        private string nombreYApellidoField;
        
        private string reparticionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cargo
        {
            get
            {
                return this.cargoField;
            }
            set
            {
                this.cargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreYApellido
        {
            get
            {
                return this.nombreYApellidoField;
            }
            set
            {
                this.nombreYApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string reparticion
        {
            get
            {
                return this.reparticionField;
            }
            set
            {
                this.reparticionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class requestExternalGenerarDocumentoVersionado : requestExternalGenerarDocumento
    {
        
        private string numeroGEDOVersionadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroGEDOVersionado
        {
            get
            {
                return this.numeroGEDOVersionadoField;
            }
            set
            {
                this.numeroGEDOVersionadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class ErrorGeneracionDocumentoException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class ClavesFaltantesException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class CantidadDatosNoSoportadaException
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", ConfigurationName="Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService")]
    public interface IExternalGenerarDocumentoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ParametroInvalidoException), Action="", Name="ParametroInvalidoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ErrorGeneracionDocumentoException), Action="", Name="ErrorGeneracionDocumentoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ClavesFaltantesException), Action="", Name="ClavesFaltantesException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.CantidadDatosNoSoportadaException), Action="", Name="CantidadDatosNoSoportadaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestExternalGenerarDocumento))]
        System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOVersionadoResponse> generarDocumentoGEDOVersionadoAsync(Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOVersionado request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ParametroInvalidoException), Action="", Name="ParametroInvalidoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ErrorGeneracionDocumentoException), Action="", Name="ErrorGeneracionDocumentoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ClavesFaltantesException), Action="", Name="ClavesFaltantesException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.CantidadDatosNoSoportadaException), Action="", Name="CantidadDatosNoSoportadaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestExternalGenerarDocumento))]
        System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOResponse> generarDocumentoGEDOAsync(Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDO request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ParametroInvalidoException), Action="", Name="ParametroInvalidoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ErrorGeneracionDocumentoException), Action="", Name="ErrorGeneracionDocumentoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ClavesFaltantesException), Action="", Name="ClavesFaltantesException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.CantidadDatosNoSoportadaException), Action="", Name="CantidadDatosNoSoportadaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestExternalGenerarDocumento))]
        System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOTemplateResponse> generarDocumentoGEDOTemplateAsync(Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOTemplate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ParametroInvalidoException), Action="", Name="ParametroInvalidoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ErrorGeneracionDocumentoException), Action="", Name="ErrorGeneracionDocumentoException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.ClavesFaltantesException), Action="", Name="ClavesFaltantesException")]
        [System.ServiceModel.FaultContractAttribute(typeof(Services.Gedo.GenerarDocumentoCnn.CantidadDatosNoSoportadaException), Action="", Name="CantidadDatosNoSoportadaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestExternalGenerarDocumento))]
        System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoUsuarioExternoResponse> generarDocumentoUsuarioExternoAsync(Services.Gedo.GenerarDocumentoCnn.generarDocumentoUsuarioExterno request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarDocumentoGEDOVersionado", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", IsWrapped=true)]
    public partial class generarDocumentoGEDOVersionado
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumentoVersionado request;
        
        public generarDocumentoGEDOVersionado()
        {
        }
        
        public generarDocumentoGEDOVersionado(Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumentoVersionado request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarDocumentoGEDOVersionadoResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", IsWrapped=true)]
    public partial class generarDocumentoGEDOVersionadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.GenerarDocumentoCnn.responseExternalGenerarDocumento @return;
        
        public generarDocumentoGEDOVersionadoResponse()
        {
        }
        
        public generarDocumentoGEDOVersionadoResponse(Services.Gedo.GenerarDocumentoCnn.responseExternalGenerarDocumento @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarDocumentoGEDO", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", IsWrapped=true)]
    public partial class generarDocumentoGEDO
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumento request;
        
        public generarDocumentoGEDO()
        {
        }
        
        public generarDocumentoGEDO(Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumento request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarDocumentoGEDOResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", IsWrapped=true)]
    public partial class generarDocumentoGEDOResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.GenerarDocumentoCnn.responseExternalGenerarDocumento @return;
        
        public generarDocumentoGEDOResponse()
        {
        }
        
        public generarDocumentoGEDOResponse(Services.Gedo.GenerarDocumentoCnn.responseExternalGenerarDocumento @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class requestExternalGenerarDocumentoTemplate
    {
        
        private string acronimoTipoDocumentoField;
        
        private byte[] dataField;
        
        private archivoEmbebidoDTO[] listaArchivosEmbebidosField;
        
        private string[] listaUsuariosDestinatariosField;
        
        private string[] listaUsuariosDestinatariosCopiaField;
        
        private string[] listaUsuariosDestinatariosCopiaOcultaField;
        
        private requestExternalGenerarDocumentoTemplateEntry[] listaUsuariosDestinatariosExternosField;
        
        private string mensajeDestinatarioField;
        
        private requestExternalGenerarDocumentoTemplateEntry1[] metaDatosField;
        
        private string referenciaField;
        
        private string sistemaOrigenField;
        
        private string tipoArchivoField;
        
        private string usuarioField;
        
        private valorFormCompDTO[] valorFormCompsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string acronimoTipoDocumento
        {
            get
            {
                return this.acronimoTipoDocumentoField;
            }
            set
            {
                this.acronimoTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaArchivosEmbebidos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public archivoEmbebidoDTO[] listaArchivosEmbebidos
        {
            get
            {
                return this.listaArchivosEmbebidosField;
            }
            set
            {
                this.listaArchivosEmbebidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaUsuariosDestinatarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string[] listaUsuariosDestinatarios
        {
            get
            {
                return this.listaUsuariosDestinatariosField;
            }
            set
            {
                this.listaUsuariosDestinatariosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaUsuariosDestinatariosCopia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string[] listaUsuariosDestinatariosCopia
        {
            get
            {
                return this.listaUsuariosDestinatariosCopiaField;
            }
            set
            {
                this.listaUsuariosDestinatariosCopiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaUsuariosDestinatariosCopiaOculta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string[] listaUsuariosDestinatariosCopiaOculta
        {
            get
            {
                return this.listaUsuariosDestinatariosCopiaOcultaField;
            }
            set
            {
                this.listaUsuariosDestinatariosCopiaOcultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public requestExternalGenerarDocumentoTemplateEntry[] listaUsuariosDestinatariosExternos
        {
            get
            {
                return this.listaUsuariosDestinatariosExternosField;
            }
            set
            {
                this.listaUsuariosDestinatariosExternosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string mensajeDestinatario
        {
            get
            {
                return this.mensajeDestinatarioField;
            }
            set
            {
                this.mensajeDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public requestExternalGenerarDocumentoTemplateEntry1[] metaDatos
        {
            get
            {
                return this.metaDatosField;
            }
            set
            {
                this.metaDatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string sistemaOrigen
        {
            get
            {
                return this.sistemaOrigenField;
            }
            set
            {
                this.sistemaOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tipoArchivo
        {
            get
            {
                return this.tipoArchivoField;
            }
            set
            {
                this.tipoArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valorFormComps", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public valorFormCompDTO[] valorFormComps
        {
            get
            {
                return this.valorFormCompsField;
            }
            set
            {
                this.valorFormCompsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class requestExternalGenerarDocumentoTemplateEntry
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class requestExternalGenerarDocumentoTemplateEntry1
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/")]
    public partial class valorFormCompDTO
    {
        
        private string inputNameField;
        
        private byte[] valorBlobField;
        
        private bool valorBooleanField;
        
        private bool valorBooleanFieldSpecified;
        
        private System.DateTime valorDateField;
        
        private bool valorDateFieldSpecified;
        
        private double valorDoubleField;
        
        private bool valorDoubleFieldSpecified;
        
        private long valorLongField;
        
        private bool valorLongFieldSpecified;
        
        private string valorStrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string inputName
        {
            get
            {
                return this.inputNameField;
            }
            set
            {
                this.inputNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] valorBlob
        {
            get
            {
                return this.valorBlobField;
            }
            set
            {
                this.valorBlobField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool valorBoolean
        {
            get
            {
                return this.valorBooleanField;
            }
            set
            {
                this.valorBooleanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorBooleanSpecified
        {
            get
            {
                return this.valorBooleanFieldSpecified;
            }
            set
            {
                this.valorBooleanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime valorDate
        {
            get
            {
                return this.valorDateField;
            }
            set
            {
                this.valorDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorDateSpecified
        {
            get
            {
                return this.valorDateFieldSpecified;
            }
            set
            {
                this.valorDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double valorDouble
        {
            get
            {
                return this.valorDoubleField;
            }
            set
            {
                this.valorDoubleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorDoubleSpecified
        {
            get
            {
                return this.valorDoubleFieldSpecified;
            }
            set
            {
                this.valorDoubleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long valorLong
        {
            get
            {
                return this.valorLongField;
            }
            set
            {
                this.valorLongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorLongSpecified
        {
            get
            {
                return this.valorLongFieldSpecified;
            }
            set
            {
                this.valorLongFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string valorStr
        {
            get
            {
                return this.valorStrField;
            }
            set
            {
                this.valorStrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarDocumentoGEDOTemplate", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", IsWrapped=true)]
    public partial class generarDocumentoGEDOTemplate
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumentoTemplate request;
        
        public generarDocumentoGEDOTemplate()
        {
        }
        
        public generarDocumentoGEDOTemplate(Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumentoTemplate request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarDocumentoGEDOTemplateResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", IsWrapped=true)]
    public partial class generarDocumentoGEDOTemplateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.GenerarDocumentoCnn.responseExternalGenerarDocumento @return;
        
        public generarDocumentoGEDOTemplateResponse()
        {
        }
        
        public generarDocumentoGEDOTemplateResponse(Services.Gedo.GenerarDocumentoCnn.responseExternalGenerarDocumento @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarDocumentoUsuarioExterno", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", IsWrapped=true)]
    public partial class generarDocumentoUsuarioExterno
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumentoUsuarioExterno request;
        
        public generarDocumentoUsuarioExterno()
        {
        }
        
        public generarDocumentoUsuarioExterno(Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumentoUsuarioExterno request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarDocumentoUsuarioExternoResponse", WrapperNamespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", IsWrapped=true)]
    public partial class generarDocumentoUsuarioExternoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ar.gob.gcaba.gedo.satra.services.external.generardocumento/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Services.Gedo.GenerarDocumentoCnn.responseExternalGenerarDocumento @return;
        
        public generarDocumentoUsuarioExternoResponse()
        {
        }
        
        public generarDocumentoUsuarioExternoResponse(Services.Gedo.GenerarDocumentoCnn.responseExternalGenerarDocumento @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IExternalGenerarDocumentoServiceChannel : Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ExternalGenerarDocumentoServiceClient : System.ServiceModel.ClientBase<Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService>, Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ExternalGenerarDocumentoServiceClient() : 
                base(ExternalGenerarDocumentoServiceClient.GetDefaultBinding(), ExternalGenerarDocumentoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IExternalGenerarDocumentoServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalGenerarDocumentoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ExternalGenerarDocumentoServiceClient.GetBindingForEndpoint(endpointConfiguration), ExternalGenerarDocumentoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalGenerarDocumentoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ExternalGenerarDocumentoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalGenerarDocumentoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ExternalGenerarDocumentoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ExternalGenerarDocumentoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOVersionadoResponse> Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService.generarDocumentoGEDOVersionadoAsync(Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOVersionado request)
        {
            return base.Channel.generarDocumentoGEDOVersionadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOVersionadoResponse> generarDocumentoGEDOVersionadoAsync(Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumentoVersionado request)
        {
            Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOVersionado inValue = new Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOVersionado();
            inValue.request = request;
            return ((Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService)(this)).generarDocumentoGEDOVersionadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOResponse> Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService.generarDocumentoGEDOAsync(Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDO request)
        {
            return base.Channel.generarDocumentoGEDOAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOResponse> generarDocumentoGEDOAsync(Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumento request)
        {
            Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDO inValue = new Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDO();
            inValue.request = request;
            return ((Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService)(this)).generarDocumentoGEDOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOTemplateResponse> Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService.generarDocumentoGEDOTemplateAsync(Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOTemplate request)
        {
            return base.Channel.generarDocumentoGEDOTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOTemplateResponse> generarDocumentoGEDOTemplateAsync(Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumentoTemplate request)
        {
            Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOTemplate inValue = new Services.Gedo.GenerarDocumentoCnn.generarDocumentoGEDOTemplate();
            inValue.request = request;
            return ((Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService)(this)).generarDocumentoGEDOTemplateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoUsuarioExternoResponse> Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService.generarDocumentoUsuarioExternoAsync(Services.Gedo.GenerarDocumentoCnn.generarDocumentoUsuarioExterno request)
        {
            return base.Channel.generarDocumentoUsuarioExternoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Services.Gedo.GenerarDocumentoCnn.generarDocumentoUsuarioExternoResponse> generarDocumentoUsuarioExternoAsync(Services.Gedo.GenerarDocumentoCnn.requestExternalGenerarDocumentoUsuarioExterno request)
        {
            Services.Gedo.GenerarDocumentoCnn.generarDocumentoUsuarioExterno inValue = new Services.Gedo.GenerarDocumentoCnn.generarDocumentoUsuarioExterno();
            inValue.request = request;
            return ((Services.Gedo.GenerarDocumentoCnn.IExternalGenerarDocumentoService)(this)).generarDocumentoUsuarioExternoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IExternalGenerarDocumentoServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IExternalGenerarDocumentoServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://mule.gdecapacitacion.lapampa.gob.ar/GEDOServices/generarDocumentoGEDO");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ExternalGenerarDocumentoServiceClient.GetBindingForEndpoint(EndpointConfiguration.IExternalGenerarDocumentoServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ExternalGenerarDocumentoServiceClient.GetEndpointAddress(EndpointConfiguration.IExternalGenerarDocumentoServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            IExternalGenerarDocumentoServicePort,
        }
    }
}
